import type { CefrLevel } from './grammar-types';

export interface GrammarRoadmapTopic {
  slug: string;
  title: string;
  title_vi: string;
  level: CefrLevel;
  order: number;
  stageNumber: number;
  stageLabel: string;
  estimatedMinutes: number;
  summary: string;
}

export interface GrammarStageInfo {
  id: CefrLevel;
  stageNumber: number;
  name: string;
  nameVi: string;
  description: string;
  topicCount: number;
}

export const GRAMMAR_STAGES: GrammarStageInfo[] = [
  {
    id: 'A0',
    stageNumber: 1,
    name: 'Foundation',
    nameVi: 'Khởi đầu & Nền tảng',
    description: 'Xây dựng viên gạch đầu tiên: đại từ, động từ to be, cấu trúc câu căn bản và quy tắc danh - tính từ.',
    topicCount: 6,
  },
  {
    id: 'A1',
    stageNumber: 2,
    name: 'Beginner',
    nameVi: 'Sơ cấp đời sống',
    description: 'Giao tiếp tình huống hàng ngày: sự tồn tại, thói quen hiện tại, câu hỏi thông dụng và mệnh lệnh.',
    topicCount: 10,
  },
  {
    id: 'A2',
    stageNumber: 3,
    name: 'Elementary',
    nameVi: 'Tiền trung cấp',
    description: 'Mở rộng ngữ cảnh thời gian, sự kiện quá khứ, dự định tương lai và so sánh tính chất.',
    topicCount: 12,
  },
  {
    id: 'B1',
    stageNumber: 4,
    name: 'Intermediate',
    nameVi: 'Trung cấp tự chủ',
    description: 'Làm chủ các thì hoàn thành, liên từ phức hợp, câu bị động, câu tường thuật và câu điều kiện.',
    topicCount: 15,
  },
  {
    id: 'B2',
    stageNumber: 5,
    name: 'Upper-Intermediate',
    nameVi: 'Nâng cao & Học thuật',
    description: 'Văn phong học thuật sắc sảo: thức giả định, đảo ngữ, câu chẻ, mệnh đề phân từ và cấu trúc nhấn mạnh.',
    topicCount: 19,
  },
];

export const UNIFIED_GRAMMAR_TOPICS: GrammarRoadmapTopic[] = [
  // ── Stage 1: A0 Foundation (Topics 1 - 6) ──
  {
    slug: 'personal-pronouns',
    title: 'Personal Pronouns',
    title_vi: 'Đại từ nhân xưng',
    level: 'A0',
    order: 1,
    stageNumber: 1,
    stageLabel: 'Stage 1: A0 Khởi đầu',
    estimatedMinutes: 15,
    summary: 'Đại từ chủ ngữ và tân ngữ: I/me, you, he/him, she/her, it, we/us, they/them.',
  },
  {
    slug: 'verb-to-be',
    title: 'Verb to be (am / is / are)',
    title_vi: 'Động từ to be (am / is / are)',
    level: 'A0',
    order: 2,
    stageNumber: 1,
    stageLabel: 'Stage 1: A0 Khởi đầu',
    estimatedMinutes: 15,
    summary: 'Dạng khẳng định, phủ định và nghi vấn của động từ to be trong câu đơn.',
  },
  {
    slug: 'demonstratives',
    title: 'Demonstratives (this/that/these/those)',
    title_vi: 'Từ chỉ định (this/that/these/those)',
    level: 'A0',
    order: 3,
    stageNumber: 1,
    stageLabel: 'Stage 1: A0 Khởi đầu',
    estimatedMinutes: 15,
    summary: 'Xác định vị trí gần/xa và số lượng đơn/nhiều với this, that, these, those.',
  },
  {
    slug: 'possessives',
    title: 'Possessive Adjectives & Pronouns',
    title_vi: 'Tính từ & đại từ sở hữu',
    level: 'A0',
    order: 4,
    stageNumber: 1,
    stageLabel: 'Stage 1: A0 Khởi đầu',
    estimatedMinutes: 15,
    summary: 'Quy tắc phân biệt tính từ sở hữu (my/your) và đại từ sở hữu (mine/yours).',
  },
  {
    slug: 'plural-nouns',
    title: 'Plural Nouns',
    title_vi: 'Danh từ số nhiều',
    level: 'A0',
    order: 5,
    stageNumber: 1,
    stageLabel: 'Stage 1: A0 Khởi đầu',
    estimatedMinutes: 15,
    summary: 'Quy tắc biến đổi danh từ số ít sang số nhiều có quy tắc (-s/-es) và bất quy tắc.',
  },
  {
    slug: 'adjectives-basic',
    title: 'Adjectives (basic)',
    title_vi: 'Tính từ cơ bản',
    level: 'A0',
    order: 6,
    stageNumber: 1,
    stageLabel: 'Stage 1: A0 Khởi đầu',
    estimatedMinutes: 15,
    summary: 'Vị trí và vai trò bổ nghĩa của tính từ trước danh từ hoặc sau to be.',
  },

  // ── Stage 2: A1 Beginner (Topics 7 - 16) ──
  {
    slug: 'there-is-there-are',
    title: 'There is / There are',
    title_vi: 'Cấu trúc There is / There are',
    level: 'A1',
    order: 7,
    stageNumber: 2,
    stageLabel: 'Stage 2: A1 Sơ cấp',
    estimatedMinutes: 15,
    summary: 'Diễn đạt sự tồn tại của người hoặc vật ở hiện tại kèm lượng từ cơ bản.',
  },
  {
    slug: 'articles',
    title: 'Articles (a / an / the)',
    title_vi: 'Mạo từ (a / an / the)',
    level: 'A1',
    order: 8,
    stageNumber: 2,
    stageLabel: 'Stage 2: A1 Sơ cấp',
    estimatedMinutes: 20,
    summary: 'Nguyên tắc sử dụng mạo từ bất định (a/an) và mạo từ xác định (the).',
  },
  {
    slug: 'present-simple',
    title: 'Present Simple',
    title_vi: 'Thì Hiện tại đơn',
    level: 'A1',
    order: 9,
    stageNumber: 2,
    stageLabel: 'Stage 2: A1 Sơ cấp',
    estimatedMinutes: 20,
    summary: 'Diễn tả thói quen, chân lý, quy tắc thêm -s/-es và trợ động từ do/does.',
  },
  {
    slug: 'have-got',
    title: 'Have got / Has got',
    title_vi: 'Cấu trúc have got / has got',
    level: 'A1',
    order: 10,
    stageNumber: 2,
    stageLabel: 'Stage 2: A1 Sơ cấp',
    estimatedMinutes: 15,
    summary: 'Diễn tả quyền sở hữu hoặc đặc điểm nhận dạng theo văn phong giao tiếp.',
  },
  {
    slug: 'wh-questions',
    title: 'Wh- Questions',
    title_vi: 'Câu hỏi với từ để hỏi (Wh-)',
    level: 'A1',
    order: 11,
    stageNumber: 2,
    stageLabel: 'Stage 2: A1 Sơ cấp',
    estimatedMinutes: 20,
    summary: 'Cấu trúc tạo câu hỏi với Who, What, Where, When, Why, Which, How.',
  },
  {
    slug: 'adverbs-frequency',
    title: 'Adverbs of Frequency',
    title_vi: 'Trạng từ chỉ tần suất',
    level: 'A1',
    order: 12,
    stageNumber: 2,
    stageLabel: 'Stage 2: A1 Sơ cấp',
    estimatedMinutes: 15,
    summary: 'Vị trí của always, usually, often, sometimes, rarely, never trong câu.',
  },
  {
    slug: 'present-continuous',
    title: 'Present Continuous',
    title_vi: 'Thì Hiện tại tiếp diễn',
    level: 'A1',
    order: 13,
    stageNumber: 2,
    stageLabel: 'Stage 2: A1 Sơ cấp',
    estimatedMinutes: 20,
    summary: 'Hành động đang diễn ra tại thời điểm nói hoặc kế hoạch tương lai xác định.',
  },
  {
    slug: 'prepositions-place',
    title: 'Prepositions of Place',
    title_vi: 'Giới từ chỉ nơi chốn',
    level: 'A1',
    order: 14,
    stageNumber: 2,
    stageLabel: 'Stage 2: A1 Sơ cấp',
    estimatedMinutes: 15,
    summary: 'Quy tắc phân biệt in, on, at, under, behind, next to, between.',
  },
  {
    slug: 'imperatives',
    title: 'Imperatives',
    title_vi: 'Câu mệnh lệnh',
    level: 'A1',
    order: 15,
    stageNumber: 2,
    stageLabel: 'Stage 2: A1 Sơ cấp',
    estimatedMinutes: 15,
    summary: 'Câu mệnh lệnh khẳng định và phủ định để đưa ra hướng dẫn, yêu cầu.',
  },
  {
    slug: 'modals-ability',
    title: 'Modals: Ability (can/could)',
    title_vi: 'Động từ khuyết thiếu: khả năng (can/could)',
    level: 'A1',
    order: 16,
    stageNumber: 2,
    stageLabel: 'Stage 2: A1 Sơ cấp',
    estimatedMinutes: 15,
    summary: 'Sử dụng can/could để diễn đạt năng lực thể chất và trí tuệ.',
  },

  // ── Stage 3: A2 Elementary (Topics 17 - 28) ──
  {
    slug: 'countable-uncountable',
    title: 'Countable & Uncountable Nouns',
    title_vi: 'Danh từ đếm được & không đếm được',
    level: 'A2',
    order: 17,
    stageNumber: 3,
    stageLabel: 'Stage 3: A2 Tiền trung cấp',
    estimatedMinutes: 20,
    summary: 'Nhận diện danh từ trừu tượng, chất liệu và cách dùng đơn vị đo lường.',
  },
  {
    slug: 'quantifiers',
    title: 'Quantifiers (some/any/much/many)',
    title_vi: 'Lượng từ (some/any/much/many)',
    level: 'A2',
    order: 18,
    stageNumber: 3,
    stageLabel: 'Stage 3: A2 Tiền trung cấp',
    estimatedMinutes: 20,
    summary: 'Phân biệt some/any, much/many, a lot of, few/little trong câu.',
  },
  {
    slug: 'prepositions-time',
    title: 'Prepositions of Time (in/on/at)',
    title_vi: 'Giới từ chỉ thời gian (in/on/at)',
    level: 'A2',
    order: 19,
    stageNumber: 3,
    stageLabel: 'Stage 3: A2 Tiền trung cấp',
    estimatedMinutes: 15,
    summary: 'Quy tắc tam giác thời gian: at (giờ), on (ngày), in (tháng/năm/mùa).',
  },
  {
    slug: 'past-simple',
    title: 'Past Simple',
    title_vi: 'Thì Quá khứ đơn',
    level: 'A2',
    order: 20,
    stageNumber: 3,
    stageLabel: 'Stage 3: A2 Tiền trung cấp',
    estimatedMinutes: 25,
    summary: 'Động từ có quy tắc (-ed) và bất quy tắc, trợ động từ did trong câu hỏi/phủ định.',
  },
  {
    slug: 'past-continuous',
    title: 'Past Continuous',
    title_vi: 'Thì Quá khứ tiếp diễn',
    level: 'A2',
    order: 21,
    stageNumber: 3,
    stageLabel: 'Stage 3: A2 Tiền trung cấp',
    estimatedMinutes: 20,
    summary: 'Hành động đang diễn ra tại mốc quá khứ hoặc hành động bị xen vào (when/while).',
  },
  {
    slug: 'be-going-to',
    title: 'Future: be going to',
    title_vi: 'Tương lai gần (be going to)',
    level: 'A2',
    order: 22,
    stageNumber: 3,
    stageLabel: 'Stage 3: A2 Tiền trung cấp',
    estimatedMinutes: 20,
    summary: 'Diễn tả kế hoạch đã lên lịch trước hoặc dự đoán có bằng chứng ở hiện tại.',
  },
  {
    slug: 'future-will',
    title: 'Future Simple (will)',
    title_vi: 'Thì Tương lai đơn (will)',
    level: 'A2',
    order: 23,
    stageNumber: 3,
    stageLabel: 'Stage 3: A2 Tiền trung cấp',
    estimatedMinutes: 20,
    summary: 'Quyết định tức thì tại thời điểm nói, lời hứa, lời đề nghị và dự đoán cảm tính.',
  },
  {
    slug: 'comparatives-superlatives',
    title: 'Comparatives & Superlatives',
    title_vi: 'So sánh hơn & so sánh nhất',
    level: 'A2',
    order: 24,
    stageNumber: 3,
    stageLabel: 'Stage 3: A2 Tiền trung cấp',
    estimatedMinutes: 25,
    summary: 'Quy tắc so sánh với tính từ ngắn, tính từ dài và các trường hợp ngoại lệ.',
  },
  {
    slug: 'modals-permission',
    title: 'Modals: Permission & Requests',
    title_vi: 'Khuyết thiếu: xin phép & yêu cầu',
    level: 'A2',
    order: 25,
    stageNumber: 3,
    stageLabel: 'Stage 3: A2 Tiền trung cấp',
    estimatedMinutes: 15,
    summary: 'Mức độ lịch sự khi dùng can, could, may, would you mind trong giao tiếp.',
  },
  {
    slug: 'modals-obligation',
    title: 'Modals: Obligation (must/have to)',
    title_vi: 'Khuyết thiếu: bắt buộc (must/have to)',
    level: 'A2',
    order: 26,
    stageNumber: 3,
    stageLabel: 'Stage 3: A2 Tiền trung cấp',
    estimatedMinutes: 20,
    summary: 'Bắt buộc chủ quan (must) đối chiếu với bắt buộc khách quan (have to).',
  },
  {
    slug: 'modals-advice',
    title: 'Modals: Advice (should/ought to)',
    title_vi: 'Khuyết thiếu: lời khuyên (should)',
    level: 'A2',
    order: 27,
    stageNumber: 3,
    stageLabel: 'Stage 3: A2 Tiền trung cấp',
    estimatedMinutes: 15,
    summary: 'Đưa ra lời khuyên hoặc ý kiến cá nhân với should, shouldn’t, ought to.',
  },
  {
    slug: 'conditionals-0-1',
    title: 'Zero & First Conditional',
    title_vi: 'Câu điều kiện loại 0 & loại 1',
    level: 'A2',
    order: 28,
    stageNumber: 3,
    stageLabel: 'Stage 3: A2 Tiền trung cấp',
    estimatedMinutes: 25,
    summary: 'Sự thật khoa học (loại 0) và tình huống có khả năng xảy ra ở tương lai (loại 1).',
  },

  // ── Stage 4: B1 Intermediate (Topics 29 - 43) ──
  {
    slug: 'used-to',
    title: 'Used to / Be used to / Get used to',
    title_vi: 'Cấu trúc Used to',
    level: 'B1',
    order: 29,
    stageNumber: 4,
    stageLabel: 'Stage 4: B1 Trung cấp',
    estimatedMinutes: 20,
    summary: 'Phân biệt thói quen trong quá khứ đã chấm dứt với trạng thái quen dần.',
  },
  {
    slug: 'present-perfect',
    title: 'Present Perfect',
    title_vi: 'Thì Hiện tại hoàn thành',
    level: 'B1',
    order: 30,
    stageNumber: 4,
    stageLabel: 'Stage 4: B1 Trung cấp',
    estimatedMinutes: 25,
    summary: 'Trải nghiệm, hành động vừa mới xảy ra, mối liên hệ hiện tại và tín hiệu since/for.',
  },
  {
    slug: 'conjunctions-linking',
    title: 'Conjunctions & Linking Words',
    title_vi: 'Liên từ & từ nối',
    level: 'B1',
    order: 31,
    stageNumber: 4,
    stageLabel: 'Stage 4: B1 Trung cấp',
    estimatedMinutes: 20,
    summary: 'Liên từ đẳng lập và phụ thuộc: although, because, however, therefore, despite.',
  },
  {
    slug: 'present-perfect-continuous',
    title: 'Present Perfect Continuous',
    title_vi: 'Hiện tại hoàn thành tiếp diễn',
    level: 'B1',
    order: 32,
    stageNumber: 4,
    stageLabel: 'Stage 4: B1 Trung cấp',
    estimatedMinutes: 20,
    summary: 'Nhấn mạnh tính liên tục của hành động kéo dài từ quá khứ đến hiện tại.',
  },
  {
    slug: 'phrasal-verbs',
    title: 'Phrasal Verbs (intro)',
    title_vi: 'Cụm động từ (nhập môn)',
    level: 'B1',
    order: 33,
    stageNumber: 4,
    stageLabel: 'Stage 4: B1 Trung cấp',
    estimatedMinutes: 25,
    summary: 'Quy tắc cụm động từ có thể tách rời và không thể tách rời trong câu.',
  },
  {
    slug: 'past-perfect',
    title: 'Past Perfect',
    title_vi: 'Thì Quá khứ hoàn thành',
    level: 'B1',
    order: 34,
    stageNumber: 4,
    stageLabel: 'Stage 4: B1 Trung cấp',
    estimatedMinutes: 20,
    summary: 'Hành động xảy ra và kết thúc trước một mốc hoặc hành động khác trong quá khứ.',
  },
  {
    slug: 'future-continuous',
    title: 'Future Continuous',
    title_vi: 'Thì Tương lai tiếp diễn',
    level: 'B1',
    order: 35,
    stageNumber: 4,
    stageLabel: 'Stage 4: B1 Trung cấp',
    estimatedMinutes: 20,
    summary: 'Hành động đang diễn ra tại một thời điểm xác định trong tương lai.',
  },
  {
    slug: 'passive-voice',
    title: 'Passive Voice',
    title_vi: 'Câu bị động',
    level: 'B1',
    order: 36,
    stageNumber: 4,
    stageLabel: 'Stage 4: B1 Trung cấp',
    estimatedMinutes: 25,
    summary: 'Chuyển đổi tân ngữ, cấu trúc bị động theo các thì và khi nào lược bỏ by-agent.',
  },
  {
    slug: 'gerunds-infinitives',
    title: 'Gerunds & Infinitives',
    title_vi: 'Danh động từ & động từ nguyên mẫu',
    level: 'B1',
    order: 37,
    stageNumber: 4,
    stageLabel: 'Stage 4: B1 Trung cấp',
    estimatedMinutes: 25,
    summary: 'Quy tắc chọn V-ing hay To-V sau các động từ đặc thù (stop, remember, forget).',
  },
  {
    slug: 'reported-speech',
    title: 'Reported Speech',
    title_vi: 'Câu tường thuật',
    level: 'B1',
    order: 38,
    stageNumber: 4,
    stageLabel: 'Stage 4: B1 Trung cấp',
    estimatedMinutes: 25,
    summary: 'Quy tắc lùi thì, biến đổi đại từ và trạng từ chỉ thời gian, nơi chốn.',
  },
  {
    slug: 'relative-clauses',
    title: 'Relative Clauses',
    title_vi: 'Mệnh đề quan hệ',
    level: 'B1',
    order: 39,
    stageNumber: 4,
    stageLabel: 'Stage 4: B1 Trung cấp',
    estimatedMinutes: 25,
    summary: 'Mệnh đề quan hệ xác định và không xác định với who, whom, which, that, whose.',
  },
  {
    slug: 'question-tags',
    title: 'Question Tags',
    title_vi: 'Câu hỏi đuôi',
    level: 'B1',
    order: 40,
    stageNumber: 4,
    stageLabel: 'Stage 4: B1 Trung cấp',
    estimatedMinutes: 20,
    summary: 'Nguyên tắc đảo dấu khẳng định - phủ định và các trường hợp đặc biệt.',
  },
  {
    slug: 'second-conditional',
    title: 'Second Conditional',
    title_vi: 'Câu điều kiện loại 2',
    level: 'B1',
    order: 41,
    stageNumber: 4,
    stageLabel: 'Stage 4: B1 Trung cấp',
    estimatedMinutes: 25,
    summary: 'Giả định một tình huống không có thật hoặc trái ngược với thực tế ở hiện tại.',
  },
  {
    slug: 'third-conditional',
    title: 'Third Conditional',
    title_vi: 'Câu điều kiện loại 3',
    level: 'B1',
    order: 42,
    stageNumber: 4,
    stageLabel: 'Stage 4: B1 Trung cấp',
    estimatedMinutes: 25,
    summary: 'Giả định trái ngược với quá khứ, diễn tả sự tiếc nuối hoặc trách móc.',
  },
  {
    slug: 'modals-deduction',
    title: 'Modals: Deduction (must/might/can\'t)',
    title_vi: 'Khuyết thiếu: suy đoán (must/might/can\'t)',
    level: 'B1',
    order: 43,
    stageNumber: 4,
    stageLabel: 'Stage 4: B1 Trung cấp',
    estimatedMinutes: 20,
    summary: 'Mức độ tin cậy của suy đoán logic ở hiện tại: must be, might be, cannot be.',
  },

  // ── Stage 5: B2 Upper-Intermediate (Topics 44 - 62) ──
  {
    slug: 'past-perfect-continuous',
    title: 'Past Perfect Continuous',
    title_vi: 'Quá khứ hoàn thành tiếp diễn',
    level: 'B2',
    order: 44,
    stageNumber: 5,
    stageLabel: 'Stage 5: B2 Nâng cao',
    estimatedMinutes: 20,
    summary: 'Nhấn mạnh khoảng thời gian kéo dài của hành động trước một mốc quá khứ.',
  },
  {
    slug: 'future-perfect',
    title: 'Future Perfect',
    title_vi: 'Thì Tương lai hoàn thành',
    level: 'B2',
    order: 45,
    stageNumber: 5,
    stageLabel: 'Stage 5: B2 Nâng cao',
    estimatedMinutes: 20,
    summary: 'Hành động sẽ hoàn tất trước một thời điểm hoặc sự kiện khác trong tương lai.',
  },
  {
    slug: 'future-in-the-past',
    title: 'Future in the Past',
    title_vi: 'Tương lai trong quá khứ',
    level: 'B2',
    order: 46,
    stageNumber: 5,
    stageLabel: 'Stage 5: B2 Nâng cao',
    estimatedMinutes: 20,
    summary: 'Diễn tả dự định từ góc nhìn quá khứ với would và was/were going to.',
  },
  {
    slug: 'mixed-conditionals',
    title: 'Mixed Conditionals',
    title_vi: 'Câu điều kiện hỗn hợp',
    level: 'B2',
    order: 47,
    stageNumber: 5,
    stageLabel: 'Stage 5: B2 Nâng cao',
    estimatedMinutes: 25,
    summary: 'Kết hợp mệnh đề điều kiện quá khứ với kết quả hiện tại hoặc ngược lại.',
  },
  {
    slug: 'wish-if-only',
    title: 'Wish / If only',
    title_vi: 'Cấu trúc Wish / If only',
    level: 'B2',
    order: 48,
    stageNumber: 5,
    stageLabel: 'Stage 5: B2 Nâng cao',
    estimatedMinutes: 25,
    summary: 'Diễn tả ước muốn cho tương lai, hiện tại và tiếc nuối về sự kiện quá khứ.',
  },
  {
    slug: 'modals-perfect',
    title: 'Perfect Modals (should have, etc.)',
    title_vi: 'Khuyết thiếu hoàn thành (should have...)',
    level: 'B2',
    order: 49,
    stageNumber: 5,
    stageLabel: 'Stage 5: B2 Nâng cao',
    estimatedMinutes: 25,
    summary: 'Suy đoán hoặc đánh giá hành động quá khứ với must have, should have, could have.',
  },
  {
    slug: 'causative',
    title: 'Causative (have/get something done)',
    title_vi: 'Thể nhờ/sai bảo (have/get sth done)',
    level: 'B2',
    order: 50,
    stageNumber: 5,
    stageLabel: 'Stage 5: B2 Nâng cao',
    estimatedMinutes: 20,
    summary: 'Cấu trúc nhờ vả chủ động (have S V) và bị động (have something done).',
  },
  {
    slug: 'advanced-passive',
    title: 'Advanced Passive',
    title_vi: 'Bị động nâng cao',
    level: 'B2',
    order: 51,
    stageNumber: 5,
    stageLabel: 'Stage 5: B2 Nâng cao',
    estimatedMinutes: 25,
    summary: 'Bị động khách quan (It is said that...) và bị động với động từ hai tân ngữ.',
  },
  {
    slug: 'advanced-relative-clauses',
    title: 'Advanced Relative Clauses',
    title_vi: 'Mệnh đề quan hệ nâng cao',
    level: 'B2',
    order: 52,
    stageNumber: 5,
    stageLabel: 'Stage 5: B2 Nâng cao',
    estimatedMinutes: 25,
    summary: 'Lược bỏ đại từ quan hệ, giới từ đi trước đại từ và mệnh đề quan hệ nối tiếp.',
  },
  {
    slug: 'participle-clauses',
    title: 'Participle Clauses',
    title_vi: 'Mệnh đề phân từ',
    level: 'B2',
    order: 53,
    stageNumber: 5,
    stageLabel: 'Stage 5: B2 Nâng cao',
    estimatedMinutes: 25,
    summary: 'Rút gọn mệnh đề chỉ lý do, thời gian hoặc kết quả bằng V-ing và V-ed/P2.',
  },
  {
    slug: 'ellipsis-substitution',
    title: 'Ellipsis & Substitution',
    title_vi: 'Lược bỏ & thay thế',
    level: 'B2',
    order: 54,
    stageNumber: 5,
    stageLabel: 'Stage 5: B2 Nâng cao',
    estimatedMinutes: 20,
    summary: 'Hiện tượng tỉnh lược từ ngữ và thay thế bằng so, neither, do, one/ones.',
  },
  {
    slug: 'subjunctive',
    title: 'Subjunctive',
    title_vi: 'Thức giả định',
    level: 'B2',
    order: 55,
    stageNumber: 5,
    stageLabel: 'Stage 5: B2 Nâng cao',
    estimatedMinutes: 25,
    summary: 'Cấu trúc giả định thức với suggest, demand, vital, crucial that S + V-inf.',
  },
  {
    slug: 'emphasis-structures',
    title: 'Emphasis Structures',
    title_vi: 'Cấu trúc nhấn mạnh',
    level: 'B2',
    order: 56,
    stageNumber: 5,
    stageLabel: 'Stage 5: B2 Nâng cao',
    estimatedMinutes: 20,
    summary: 'Nhấn mạnh hành động bằng do/does/did trước động từ chính và tiền trí phó từ.',
  },
  {
    slug: 'cleft-sentences',
    title: 'Cleft Sentences',
    title_vi: 'Câu chẻ (nhấn mạnh)',
    level: 'B2',
    order: 57,
    stageNumber: 5,
    stageLabel: 'Stage 5: B2 Nâng cao',
    estimatedMinutes: 25,
    summary: 'Nhấn mạnh thành phần câu với It is/was... that... và What-cleft sentences.',
  },
  {
    slug: 'inversion',
    title: 'Inversion',
    title_vi: 'Đảo ngữ',
    level: 'B2',
    order: 58,
    stageNumber: 5,
    stageLabel: 'Stage 5: B2 Nâng cao',
    estimatedMinutes: 30,
    summary: 'Đảo ngữ với phó từ phủ định (Never, Seldom, Not only), câu điều kiện và only.',
  },
  {
    slug: 'discourse-markers',
    title: 'Discourse Markers',
    title_vi: 'Từ nối diễn ngôn',
    level: 'B2',
    order: 59,
    stageNumber: 5,
    stageLabel: 'Stage 5: B2 Nâng cao',
    estimatedMinutes: 25,
    summary: 'Từ nối học thuật định hình mạch lập luận: Furthermore, In contrast, Nonetheless.',
  },
  {
    slug: 'nominalisation',
    title: 'Nominalisation',
    title_vi: 'Danh từ hóa',
    level: 'B2',
    order: 60,
    stageNumber: 5,
    stageLabel: 'Stage 5: B2 Nâng cao',
    estimatedMinutes: 25,
    summary: 'Chuyển đổi động từ/tính từ thành cụm danh từ để tăng tính học thuật và súc tích.',
  },
  {
    slug: 'hedging-language',
    title: 'Hedging Language',
    title_vi: 'Ngôn ngữ rào đón (hedging)',
    level: 'B2',
    order: 61,
    stageNumber: 5,
    stageLabel: 'Stage 5: B2 Nâng cao',
    estimatedMinutes: 25,
    summary: 'Kỹ thuật diễn đạt dè dặt, khách quan trong viết luận: appear, tend to, plausible.',
  },
  {
    slug: 'grammatical-collocations',
    title: 'Grammatical Collocations',
    title_vi: 'Kết hợp ngữ pháp (collocations)',
    level: 'B2',
    order: 62,
    stageNumber: 5,
    stageLabel: 'Stage 5: B2 Nâng cao',
    estimatedMinutes: 25,
    summary: 'Các cụm từ đi kèm giới từ và cấu trúc ngữ pháp cố định trong tiếng Anh học thuật.',
  },
];

export function getTopicBySlug(slug: string): GrammarRoadmapTopic | undefined {
  return UNIFIED_GRAMMAR_TOPICS.find((t) => t.slug === slug);
}

export function getTopicsByLevel(level: CefrLevel): GrammarRoadmapTopic[] {
  return UNIFIED_GRAMMAR_TOPICS.filter((t) => t.level === level);
}
