'use client';

/**
 * /practice/daily-reading — Bài luyện đọc hàng ngày (pre-generated by NLM)
 *
 * Tabs: Đọc | Điền từ | Từ vựng
 * Cuối bài: list từ vựng + nút lưu từ mới (bonus)
 */

import { useCallback, useEffect, useMemo, useState, type ReactNode } from 'react';
import Link from 'next/link';
import {
  BookOpen,
  Check,
  ChevronLeft,
  Loader2,
  Plus,
  Sparkles,
  BookMarked,
  Calendar,
  CheckCircle2,
  XCircle,
  Volume2,
  ChevronDown,
  ChevronUp,
} from 'lucide-react';
import { authFetch } from '@/lib/auth-fetch';
import { StudentShell } from '@/components/student/StudentShell';

// ── Types ──
interface PassageQuestion {
  q: string;
  options: string[];
  answer: string;
  explain: string;
}

interface ClozeBlank {
  id: number;
  answer: string;
  options: string[];
}

interface WordItem {
  word: string;
  translation: string;
  pos?: string;
  definition_en?: string;
}

interface DailyExercise {
  id: string;
  classroomId: string | null;
  classroomName: string;
  isPersonal?: boolean;
  exerciseDate: string;
  sourceDate: string;
  title: string;
  passage: string;
  passagePlain: string;
  translation?: string;
  level: string;
  questions: PassageQuestion[];
  cloze: { text: string; blanks: ClozeBlank[] };
  sourceWords: WordItem[];
  usedWords: string[];
  coverage: number;
  bonusWords: WordItem[];
  generatedAt: string;
  completion: {
    mcqScore: number;
    mcqTotal: number;
    clozeScore: number;
    clozeTotal: number;
    completedAt: string;
  } | null;
}

type Tab = 'passage' | 'cloze' | 'vocab';

// ── Helpers ──

function renderClozeText(
  text: string,
  blanks: ClozeBlank[],
  answers: Record<number, string>,
  onPick: (id: number, value: string) => void,
  revealed: boolean,
): ReactNode[] {
  const nodes: ReactNode[] = [];
  const re = /\{\{(\d+)\}\}/g;
  let last = 0;
  let match: RegExpExecArray | null;
  let key = 0;
  while ((match = re.exec(text)) !== null) {
    if (match.index > last) {
      nodes.push(<span key={key++}>{text.slice(last, match.index)}</span>);
    }
    const id = Number(match[1]);
    const blank = blanks.find((b) => b.id === id) ?? blanks[id];
    const selected = answers[id] ?? '';
    const correct = blank?.answer?.toLowerCase() === selected.toLowerCase();
    nodes.push(
      <span key={key++} className="mx-0.5 my-1 inline-flex flex-col align-middle">
        <select
          className={`min-w-[7rem] rounded border px-2 py-1 text-sm ${
            revealed
              ? correct
                ? 'border-emerald-500 bg-emerald-50 text-emerald-900'
                : 'border-red-400 bg-red-50 text-red-900'
              : 'border-slate-300 bg-white'
          }`}
          value={selected}
          onChange={(e) => onPick(id, e.target.value)}
          disabled={revealed}
        >
          <option value="">— chọn —</option>
          {(blank?.options ?? []).map((opt) => (
            <option key={opt} value={opt}>
              {opt}
            </option>
          ))}
        </select>
        {revealed && !correct && blank && (
          <span className="mt-0.5 text-[10px] font-bold text-emerald-700">✓ {blank.answer}</span>
        )}
      </span>,
    );
    last = match.index + match[0].length;
  }
  if (last < text.length) {
    nodes.push(<span key={key++}>{text.slice(last)}</span>);
  }
  return nodes;
}

export function renderFormattedPassage(text: string, sourceWords?: WordItem[]): ReactNode {
  if (!text) return null;
  const wordMap = new Map<string, string>();
  for (const w of sourceWords || []) {
    if (w.word && w.translation) {
      wordMap.set(w.word.trim().toLowerCase(), w.translation.trim());
    }
  }

  const parts = text.split(/(\*\*[^*]+\*\*)/g);
  return parts.map((part, i) => {
    if (part.startsWith('**') && part.endsWith('**')) {
      const target = part.slice(2, -2);
      const trans = wordMap.get(target.trim().toLowerCase());
      return (
        <strong
          key={i}
          title={trans ? `${target}: ${trans}` : target}
          className="group relative inline-block font-bold text-indigo-700 bg-indigo-50/90 hover:bg-indigo-100 hover:text-indigo-900 px-1.5 py-0.5 rounded transition-colors cursor-help"
        >
          {target}
          {trans && (
            <span className="hidden group-hover:inline-block absolute bottom-full left-1/2 -translate-x-1/2 mb-1.5 px-2 py-1 text-[11px] font-medium text-white bg-slate-900/95 backdrop-blur rounded shadow-lg whitespace-nowrap z-30 pointer-events-none">
              {target}: {trans}
            </span>
          )}
        </strong>
      );
    }
    return part;
  });
}

function formatDate(dateStr: string): string {
  try {
    const d = new Date(dateStr + 'T00:00:00+07:00');
    return d.toLocaleDateString('vi-VN', { weekday: 'long', day: 'numeric', month: 'long' });
  } catch {
    return dateStr;
  }
}

// ── Component ──
export default function DailyReadingPage() {
  const [exercises, setExercises] = useState<DailyExercise[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [selectedIdx, setSelectedIdx] = useState(0);

  const [tab, setTab] = useState<Tab>('passage');
  const [showTranslation, setShowTranslation] = useState(false);

  // MCQ state
  const [qAnswers, setQAnswers] = useState<Record<number, string>>({});
  const [qRevealed, setQRevealed] = useState(false);

  // Cloze state
  const [clozeAnswers, setClozeAnswers] = useState<Record<number, string>>({});
  const [clozeRevealed, setClozeRevealed] = useState(false);
  const [showWordBank, setShowWordBank] = useState(true);

  // Save word state
  const [savedWords, setSavedWords] = useState<Set<string>>(() => new Set());
  const [savingWord, setSavingWord] = useState<string | null>(null);

  // Fetch exercises
  useEffect(() => {
    let cancelled = false;
    (async () => {
      setLoading(true);
      try {
        const res = await authFetch('/api/practice/daily-reading?recent=3');
        const json = await res.json();
        if (!cancelled) {
          if (json.success && Array.isArray(json.exercises)) {
            setExercises(json.exercises);
          } else {
            setError(json.error || 'Không tải được bài tập');
          }
        }
      } catch (e) {
        if (!cancelled) setError(e instanceof Error ? e.message : 'Lỗi kết nối');
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => { cancelled = true; };
  }, []);

  const exercise = exercises[selectedIdx] ?? null;

  // Handle switching exercises without cascading useEffect renders
  const handleSelectExercise = (idx: number) => {
    if (idx === selectedIdx) return;
    setSelectedIdx(idx);
    setQAnswers({});
    setQRevealed(false);
    setClozeAnswers({});
    setClozeRevealed(false);
    setShowWordBank(true);
    setShowTranslation(false);
    setTab('passage');
  };

  // MCQ score
  const qScore = useMemo(() => {
    if (!exercise || !qRevealed) return null;
    let ok = 0;
    exercise.questions.forEach((q, i) => {
      if ((qAnswers[i] || '').trim() === q.answer.trim()) ok++;
    });
    return { ok, total: exercise.questions.length };
  }, [exercise, qAnswers, qRevealed]);

  // Identify blanks that actually appear in the cloze text
  const textBlankIds = useMemo(() => {
    if (!exercise?.cloze?.text) return [];
    const matches = Array.from(exercise.cloze.text.matchAll(/\{\{(\d+)\}\}/g));
    const ids = new Set<number>();
    for (const m of matches) {
      const id = Number(m[1]);
      if (exercise.cloze.blanks.some((b) => b.id === id) || exercise.cloze.blanks[id]) {
        ids.add(id);
      }
    }
    return Array.from(ids);
  }, [exercise]);

  // Cloze score (grounded on blanks actually present in text)
  const clozeScore = useMemo(() => {
    if (!exercise || !clozeRevealed) return null;
    let ok = 0;
    const targetIds = textBlankIds.length > 0 ? textBlankIds : exercise.cloze.blanks.map((b) => b.id);
    targetIds.forEach((id) => {
      const blank = exercise.cloze.blanks.find((b) => b.id === id) ?? exercise.cloze.blanks[id];
      if (blank && (clozeAnswers[id] || '').toLowerCase() === blank.answer.toLowerCase()) {
        ok++;
      }
    });
    return { ok, total: targetIds.length };
  }, [exercise, clozeAnswers, clozeRevealed, textBlankIds]);

  // Derived word bank for Cloze
  const wordBank = useMemo(() => {
    if (!exercise) return [];
    const words = new Set<string>();
    exercise.cloze.blanks.forEach((b) => words.add(b.answer));
    return Array.from(words).sort();
  }, [exercise]);

  // Cloze submission readiness: every visible blank must be filled
  const canSubmitCloze = useMemo(() => {
    if (!exercise) return false;
    const targetIds = textBlankIds.length > 0 ? textBlankIds : exercise.cloze.blanks.map((b) => b.id);
    if (targetIds.length === 0) return false;
    return targetIds.every((id) => Boolean((clozeAnswers[id] || '').trim()));
  }, [exercise, textBlankIds, clozeAnswers]);

  // Submit completion (allows saving MCQ and Cloze independently while preserving prior section score)
  const submitCompletion = useCallback(
    async (mcqScoreVal: number, mcqTotalVal: number, clozeScoreVal: number, clozeTotalVal: number) => {
      if (!exercise) return;
      try {
        await authFetch('/api/practice/daily-reading', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            exerciseId: exercise.id,
            mcqScore: mcqScoreVal,
            mcqTotal: mcqTotalVal,
            clozeScore: clozeScoreVal,
            clozeTotal: clozeTotalVal,
          }),
        });

        // Optimistically update local exercise completion state
        setExercises((prev) =>
          prev.map((e) =>
            e.id === exercise.id
              ? {
                  ...e,
                  completion: {
                    mcqScore: mcqScoreVal,
                    mcqTotal: mcqTotalVal,
                    clozeScore: clozeScoreVal,
                    clozeTotal: clozeTotalVal,
                    completedAt: new Date().toISOString(),
                  },
                }
              : e,
          ),
        );
      } catch {
        // Non-critical
      }
    },
    [exercise],
  );

  const handleGradeMcq = useCallback(() => {
    setQRevealed(true);
    if (!exercise) return;
    let ok = 0;
    exercise.questions.forEach((q, i) => {
      if ((qAnswers[i] || '').trim() === q.answer.trim()) ok++;
    });
    const finalMcqScore = ok;
    const finalMcqTotal = exercise.questions.length;
    const finalClozeScore = clozeScore?.ok ?? exercise.completion?.clozeScore ?? 0;
    const targetClozeTotal =
      textBlankIds.length > 0 ? textBlankIds.length : exercise.cloze.blanks.length;
    const finalClozeTotal =
      clozeScore?.total ?? exercise.completion?.clozeTotal ?? targetClozeTotal;
    void submitCompletion(finalMcqScore, finalMcqTotal, finalClozeScore, finalClozeTotal);
  }, [exercise, qAnswers, clozeScore, textBlankIds, submitCompletion]);

  const handleGradeCloze = useCallback(() => {
    setClozeRevealed(true);
    if (!exercise) return;
    let ok = 0;
    const targetIds =
      textBlankIds.length > 0 ? textBlankIds : exercise.cloze.blanks.map((b) => b.id);
    targetIds.forEach((id) => {
      const blank = exercise.cloze.blanks.find((b) => b.id === id) ?? exercise.cloze.blanks[id];
      if (blank && (clozeAnswers[id] || '').toLowerCase() === blank.answer.toLowerCase()) {
        ok++;
      }
    });
    const finalClozeScore = ok;
    const finalClozeTotal = targetIds.length;
    const finalMcqScore = qScore?.ok ?? exercise.completion?.mcqScore ?? 0;
    const finalMcqTotal = exercise.completion?.mcqTotal ?? exercise.questions.length;
    void submitCompletion(finalMcqScore, finalMcqTotal, finalClozeScore, finalClozeTotal);
  }, [exercise, clozeAnswers, qScore, textBlankIds, submitCompletion]);

  // Save bonus word
  const saveWord = useCallback(
    async (w: WordItem) => {
      if (!exercise || savedWords.has(w.word)) return;
      setSavingWord(w.word);
      try {
        const res = await authFetch('/api/practice/daily-reading/save-word', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            word: w.word,
            translation: w.translation,
            pos: w.pos,
            classroomId: exercise.classroomId || undefined,
            exerciseId: exercise.id,
          }),
        });
        const json = await res.json();
        if (json.success) {
          setSavedWords((prev) => new Set(prev).add(w.word));
        }
      } catch {
        // Ignore
      } finally {
        setSavingWord(null);
      }
    },
    [exercise, savedWords],
  );

  // ── Render ──
  return (
    <StudentShell title="Bài đọc hàng ngày">
      <div className="mx-auto max-w-5xl space-y-3 px-3 py-3 pb-24 sm:px-4">
        {/* Header */}
        <div className="flex items-center gap-2">
          <Link
            href="/practice"
            className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg border bg-white text-slate-600"
            aria-label="Về Sử dụng từ"
          >
            <ChevronLeft className="h-4 w-4" />
          </Link>
          <div className="min-w-0 flex-1">
            <div className="flex items-center gap-1.5">
              <h1 className="text-base font-black text-slate-900">Bài đọc hàng ngày</h1>
              <span className="inline-flex items-center gap-0.5 rounded-full border border-indigo-200 bg-indigo-50 px-1.5 py-0.5 text-[10px] font-bold text-indigo-700">
                <Sparkles className="h-2.5 w-2.5" /> NLM
              </span>
            </div>
            <p className="text-[11px] text-slate-500">Tạo tự động từ từ vựng hôm qua</p>
          </div>
          <BookOpen className="h-5 w-5 shrink-0 text-indigo-600" />
        </div>

        {/* Loading / Error / Empty */}
        {loading && (
          <div className="flex items-center justify-center gap-2 py-12 text-sm text-slate-500">
            <Loader2 className="h-4 w-4 animate-spin" /> Đang tải bài tập…
          </div>
        )}

        {error && (
          <div className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-xs text-red-800">
            {error}
          </div>
        )}

        {!loading && !error && exercises.length === 0 && (
          <div className="mx-auto max-w-2xl rounded-2xl border border-amber-200/80 bg-gradient-to-b from-amber-50/90 to-amber-50/40 p-6 text-center shadow-sm">
            <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-amber-100 text-amber-600 ring-4 ring-amber-50">
              <BookMarked className="h-7 w-7" />
            </div>
            <h2 className="mt-3 text-base font-black text-slate-900">
              Chưa có bài đọc cá nhân hóa hôm nay
            </h2>
            <p className="mt-1.5 text-xs text-slate-600 max-w-md mx-auto leading-relaxed">
              Hệ thống tự động phân tích cấp độ và tạo bài đọc riêng biệt cho bạn vào lúc <strong>2:00 AM</strong> mỗi đêm dựa trên từ vựng mới lưu trong ngày kết hợp các từ đến hạn ôn tập SRS.
            </p>
            <div className="mt-4 rounded-xl border border-amber-200/60 bg-white/80 p-3 text-left max-w-md mx-auto text-[11px] text-slate-600 space-y-1">
              <div className="flex items-center gap-1.5 font-bold text-amber-900">
                <Sparkles className="h-3.5 w-3.5 text-amber-500" />
                <span>Điều kiện tạo bài đọc tự động:</span>
              </div>
              <p>• Từ nâng cao (B2–C1): Chỉ cần lưu từ <strong>3 từ</strong>.</p>
              <p>• Từ cơ bản (A1–B1): Cần tích lũy từ <strong>5 từ</strong>.</p>
              <p className="text-[10px] text-slate-500 italic">Nếu chưa đủ từ mới, hệ thống tự động bù bằng từ đến hạn ôn tập SRS của bạn.</p>
            </div>
            <div className="mt-5 flex flex-wrap items-center justify-center gap-2">
              <Link
                href="/dictionary"
                className="inline-flex items-center gap-1.5 rounded-xl bg-indigo-600 px-3.5 py-2 text-xs font-bold text-white shadow-sm hover:bg-indigo-700 transition-colors"
              >
                <Plus className="h-3.5 w-3.5" /> Tra & lưu từ mới
              </Link>
              <Link
                href="/review"
                className="inline-flex items-center gap-1.5 rounded-xl border border-slate-200 bg-white px-3.5 py-2 text-xs font-bold text-slate-700 shadow-sm hover:bg-slate-50 transition-colors"
              >
                Ôn tập SRS
              </Link>
              <Link
                href="/flashcard"
                className="inline-flex items-center gap-1.5 rounded-xl border border-amber-300 bg-amber-100/70 px-3.5 py-2 text-xs font-bold text-amber-900 hover:bg-amber-200/70 transition-colors"
              >
                Học flashcard
              </Link>
            </div>
          </div>
        )}

        {/* Exercise selector (if multiple) */}
        {exercises.length > 1 && (
          <div className="flex gap-1.5 overflow-x-auto pb-1">
            {exercises.map((ex, idx) => (
              <button
                key={ex.id}
                type="button"
                onClick={() => handleSelectExercise(idx)}
                className={`shrink-0 rounded-lg border px-2.5 py-1.5 text-xs font-bold transition-colors ${
                  idx === selectedIdx
                    ? 'border-indigo-400 bg-indigo-50 text-indigo-800'
                    : 'border-slate-200 text-slate-500 hover:border-slate-300'
                }`}
              >
                <Calendar className="mr-1 inline h-3 w-3" />
                {formatDate(ex.exerciseDate)}
                {ex.completion?.completedAt && (
                  <CheckCircle2 className="ml-1 inline h-3 w-3 text-emerald-500" />
                )}
              </button>
            ))}
          </div>
        )}

        {/* Exercise content */}
        {exercise && (
          <>
            {/* Title card */}
            <div className="rounded-xl border border-indigo-100 bg-gradient-to-br from-indigo-50 to-white p-3 shadow-sm">
              <div className="flex items-start justify-between gap-2">
                <div>
                  <h2 className="text-sm font-black text-slate-900">{exercise.title}</h2>
                  <div className="mt-1 flex flex-wrap items-center gap-1.5 text-[10px] text-slate-500">
                    <span className="rounded-full border border-slate-200 bg-white px-1.5 py-0.5 font-bold">
                      {exercise.level}
                    </span>
                    {exercise.isPersonal && (
                      <span className="inline-flex items-center gap-0.5 rounded-full border border-indigo-200 bg-indigo-50 px-1.5 py-0.5 font-bold text-indigo-700">
                        <Sparkles className="h-2.5 w-2.5" /> Cá nhân hóa
                      </span>
                    )}
                    <span>{exercise.classroomName}</span>
                    <span>·</span>
                    <span>{exercise.sourceWords.length} từ</span>
                    <span>·</span>
                    <span>{(exercise.coverage * 100).toFixed(0)}% coverage</span>
                    {exercise.bonusWords.length > 0 && (
                      <>
                        <span>·</span>
                        <span className="font-bold text-indigo-600">
                          +{exercise.bonusWords.length} từ mới
                        </span>
                      </>
                    )}
                  </div>
                </div>
                {exercise.completion?.completedAt && (
                  <span className="shrink-0 rounded-full bg-emerald-100 px-2 py-0.5 text-[10px] font-bold text-emerald-700">
                    ✓ Đã làm
                  </span>
                )}
              </div>
            </div>

            {/* Tabs */}
            <div className="flex rounded-xl border border-slate-200 bg-slate-50 p-0.5">
              {([
                { id: 'passage' as Tab, label: 'Đọc', icon: BookOpen },
                { id: 'cloze' as Tab, label: 'Điền từ', icon: BookMarked },
                { id: 'vocab' as Tab, label: 'Từ vựng', icon: Volume2 },
              ]).map((t) => (
                <button
                  key={t.id}
                  type="button"
                  onClick={() => setTab(t.id)}
                  className={`flex flex-1 items-center justify-center gap-1 rounded-lg py-2 text-xs font-bold transition-all ${
                    tab === t.id
                      ? 'bg-white text-indigo-700 shadow-sm'
                      : 'text-slate-500 hover:text-slate-700'
                  }`}
                >
                  <t.icon className="h-3.5 w-3.5" />
                  {t.label}
                </button>
              ))}
            </div>

            {/* Tab: Passage + MCQ */}
            {tab === 'passage' && (
              <div className="flex flex-col lg:grid lg:grid-cols-3 lg:gap-6 lg:space-y-0 space-y-4">
                {/* Passage (Left 2/3) */}
                <div className="lg:col-span-2">
                  <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm lg:sticky lg:top-4">
                    <p className="whitespace-pre-line text-sm leading-[1.8] text-slate-800">
                      {renderFormattedPassage(exercise.passage || exercise.passagePlain, exercise.sourceWords)}
                    </p>
                    
                    {exercise.translation && (
                      <div className="mt-5 border-t border-slate-100 pt-4">
                        <button
                          type="button"
                          onClick={() => setShowTranslation(!showTranslation)}
                          className="inline-flex items-center gap-1.5 rounded-lg border border-indigo-200 bg-indigo-50 px-3 py-1.5 text-xs font-bold text-indigo-700 hover:bg-indigo-100 transition-colors shadow-sm"
                        >
                          <BookOpen className="h-3.5 w-3.5" />
                          {showTranslation ? 'Ẩn bản dịch tiếng Việt' : '📖 Xem bản dịch tiếng Việt'}
                        </button>
                        
                        {showTranslation && (
                          <div className="mt-3 rounded-xl bg-slate-50 p-4 border border-slate-200/80 shadow-sm">
                            <div className="flex items-center gap-1.5 mb-2 text-xs font-bold text-indigo-900 uppercase tracking-wider">
                              <Sparkles className="h-3.5 w-3.5 text-indigo-600" />
                              <span>Bản dịch tiếng Việt tham khảo:</span>
                            </div>
                            <p className="whitespace-pre-line text-sm leading-[1.8] text-slate-700">
                              {exercise.translation}
                            </p>
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                </div>

                {/* MCQ (Right 1/3) */}
                <div className="lg:col-span-1 space-y-3">
                  <h3 className="text-sm font-black text-slate-700 border-b border-slate-200 pb-2">
                    Câu hỏi ({exercise.questions.length})
                  </h3>

                  {exercise.questions.map((q, qi) => {
                    const picked = qAnswers[qi] ?? '';
                    const isCorrect = picked.trim() === q.answer.trim();

                    return (
                      <div
                        key={qi}
                        className={`rounded-xl border p-3 ${
                          qRevealed
                            ? isCorrect
                              ? 'border-emerald-200 bg-emerald-50/50'
                              : 'border-red-200 bg-red-50/50'
                            : 'border-slate-200 bg-white'
                        }`}
                      >
                        <p className="text-xs font-bold text-slate-800">
                          {qi + 1}. {q.q}
                        </p>
                        <div className="mt-2 space-y-1.5">
                          {q.options.map((opt) => {
                            const selected = picked === opt;
                            const isAnswer = opt.trim() === q.answer.trim();
                            let cls = 'border-slate-200 bg-white text-slate-700';
                            if (qRevealed) {
                              if (isAnswer) cls = 'border-emerald-400 bg-emerald-50 text-emerald-900 font-bold';
                              else if (selected) cls = 'border-red-400 bg-red-50 text-red-800';
                              else cls = 'border-slate-100 bg-slate-50 text-slate-400';
                            } else if (selected) {
                              cls = 'border-indigo-400 bg-indigo-50 text-indigo-800 font-semibold';
                            }
                            return (
                              <button
                                key={opt}
                                type="button"
                                disabled={qRevealed}
                                onClick={() =>
                                  setQAnswers((prev) => ({ ...prev, [qi]: opt }))
                                }
                                className={`block w-full rounded-lg border px-3 py-2 text-left text-xs transition-colors ${cls}`}
                              >
                                {qRevealed && isAnswer && (
                                  <CheckCircle2 className="mr-1 inline h-3 w-3 text-emerald-600" />
                                )}
                                {qRevealed && selected && !isAnswer && (
                                  <XCircle className="mr-1 inline h-3 w-3 text-red-500" />
                                )}
                                {opt}
                              </button>
                            );
                          })}
                        </div>

                        {qRevealed && q.explain && (
                          <p className="mt-2 rounded-lg bg-slate-100 px-2.5 py-1.5 text-[11px] text-slate-600">
                            💡 {q.explain}
                          </p>
                        )}
                      </div>
                    );
                  })}

                  {/* Submit / Score */}
                  {!qRevealed ? (
                    <button
                      type="button"
                      onClick={handleGradeMcq}
                      disabled={Object.keys(qAnswers).length < exercise.questions.length}
                      className="w-full rounded-xl bg-indigo-600 py-2.5 text-sm font-bold text-white hover:bg-indigo-700 disabled:opacity-40"
                    >
                      Chấm điểm
                    </button>
                  ) : qScore && (
                    <div
                      className={`rounded-xl border p-3 text-center ${
                        qScore.ok === qScore.total
                          ? 'border-emerald-200 bg-emerald-50'
                          : qScore.ok >= qScore.total / 2
                            ? 'border-amber-200 bg-amber-50'
                            : 'border-red-200 bg-red-50'
                      }`}
                    >
                      <p className="text-lg font-black">
                        {qScore.ok}/{qScore.total}
                      </p>
                      <p className="text-[11px] text-slate-600">
                        {qScore.ok === qScore.total
                          ? '🎉 Xuất sắc!'
                          : qScore.ok >= qScore.total / 2
                            ? '👏 Khá tốt!'
                            : '💪 Cần ôn thêm!'}
                      </p>
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* Tab: Cloze */}
            {tab === 'cloze' && (
              <div className="space-y-3">
                {/* Word Bank */}
                <div className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm">
                  <button
                    type="button"
                    onClick={() => setShowWordBank(!showWordBank)}
                    className="flex w-full items-center justify-between text-left"
                  >
                    <span className="text-xs font-black text-slate-700">
                      💡 Tổng hợp từ cần điền ({wordBank.length})
                    </span>
                    {showWordBank ? (
                      <ChevronUp className="h-4 w-4 text-slate-400" />
                    ) : (
                      <ChevronDown className="h-4 w-4 text-slate-400" />
                    )}
                  </button>
                  {showWordBank && (
                    <div className="mt-3 flex flex-wrap gap-2 border-t border-slate-100 pt-3">
                      {wordBank.map((w) => {
                        // Count how many times it's been used in answers
                        const usedCount = Object.values(clozeAnswers).filter(
                          (a) => a.toLowerCase() === w.toLowerCase(),
                        ).length;
                        const isFullyUsed =
                          usedCount >=
                          exercise.cloze.blanks.filter((b) => b.answer.toLowerCase() === w.toLowerCase())
                            .length;

                        return (
                          <span
                            key={w}
                            className={`rounded-lg px-2.5 py-1 text-xs font-bold transition-all ${
                              isFullyUsed
                                ? 'bg-slate-100 text-slate-400 line-through'
                                : 'bg-indigo-50 text-indigo-700'
                            }`}
                          >
                            {w}
                          </span>
                        );
                      })}
                    </div>
                  )}
                </div>

                <div className="rounded-xl border border-slate-200 bg-white p-3.5 shadow-sm">
                  <p className="whitespace-pre-line text-[13px] leading-[2] text-slate-800">
                    {renderClozeText(
                      exercise.cloze.text,
                      exercise.cloze.blanks,
                      clozeAnswers,
                      (id, val) => setClozeAnswers((prev) => ({ ...prev, [id]: val })),
                      clozeRevealed,
                    )}
                  </p>
                </div>

                {!clozeRevealed ? (
                  <button
                    type="button"
                    onClick={handleGradeCloze}
                    disabled={!canSubmitCloze}
                    className="w-full rounded-xl bg-indigo-600 py-2.5 text-sm font-bold text-white hover:bg-indigo-700 disabled:opacity-40"
                  >
                    Chấm điểm
                  </button>
                ) : clozeScore && (
                  <div
                    className={`rounded-xl border p-3 text-center ${
                      clozeScore.ok === clozeScore.total
                        ? 'border-emerald-200 bg-emerald-50'
                        : clozeScore.ok >= clozeScore.total / 2
                          ? 'border-amber-200 bg-amber-50'
                          : 'border-red-200 bg-red-50'
                    }`}
                  >
                    <p className="text-lg font-black">
                      {clozeScore.ok}/{clozeScore.total}
                    </p>
                    <p className="text-[11px] text-slate-600">
                      {clozeScore.ok === clozeScore.total
                        ? '🎉 Hoàn hảo!'
                        : clozeScore.ok >= clozeScore.total / 2
                          ? '👏 Tốt lắm!'
                          : '💪 Thử lại nhé!'}
                    </p>
                  </div>
                )}
              </div>
            )}

            {/* Tab: Vocabulary */}
            {tab === 'vocab' && (
              <div className="space-y-3">
                {/* Source words (đã học) */}
                <div className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm">
                  <h3 className="mb-2 text-xs font-black text-slate-700">
                    📚 Từ trong bài ({exercise.sourceWords.length})
                  </h3>
                  <div className="space-y-1.5">
                    {exercise.sourceWords.map((w) => {
                      const isUsed = exercise.usedWords.some(
                        (u) => u.trim().toLowerCase() === w.word.trim().toLowerCase(),
                      );
                      return (
                        <div
                          key={w.word}
                          className={`flex items-center gap-2 rounded-lg border px-3 py-2 ${
                            isUsed
                              ? 'border-emerald-100 bg-emerald-50/50'
                              : 'border-slate-100 bg-slate-50/50'
                          }`}
                        >
                          {isUsed && (
                            <Check className="h-3 w-3 shrink-0 text-emerald-500" />
                          )}
                          <div className="min-w-0 flex-1">
                            <span className="text-xs font-bold text-slate-900">{w.word}</span>
                            {w.pos && (
                              <span className="ml-1 text-[10px] text-slate-400">({w.pos})</span>
                            )}
                            <span className="ml-2 text-xs text-slate-600">{w.translation}</span>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>

                {/* Bonus words (từ mới) */}
                {exercise.bonusWords.length > 0 && (
                  <div className="rounded-xl border border-indigo-100 bg-indigo-50/30 p-3 shadow-sm">
                    <h3 className="mb-2 flex items-center gap-1 text-xs font-black text-indigo-800">
                      <Sparkles className="h-3 w-3" />
                      Từ mới trong bài ({exercise.bonusWords.length})
                    </h3>
                    <p className="mb-2 text-[10px] text-indigo-600">
                      Những từ mới xuất hiện trong bài đọc — bấm Lưu để thêm vào bộ từ của bạn!
                    </p>
                    <div className="space-y-1.5">
                      {exercise.bonusWords.map((w) => {
                        const isSaved = savedWords.has(w.word);
                        const isSaving = savingWord === w.word;
                        return (
                          <div
                            key={w.word}
                            className={`flex items-center gap-2 rounded-lg border px-3 py-2 ${
                              isSaved
                                ? 'border-emerald-200 bg-emerald-50'
                                : 'border-indigo-200 bg-white'
                            }`}
                          >
                            <div className="min-w-0 flex-1">
                              <div>
                                <span className="text-xs font-bold text-slate-900">
                                  {w.word}
                                </span>
                                {w.pos && (
                                  <span className="ml-1 text-[10px] text-slate-400">
                                    ({w.pos})
                                  </span>
                                )}
                              </div>
                              <p className="text-xs text-slate-600">{w.translation}</p>
                              {w.definition_en && (
                                <p className="text-[10px] text-slate-400 italic">
                                  {w.definition_en}
                                </p>
                              )}
                            </div>
                            <button
                              type="button"
                              disabled={isSaved || isSaving}
                              onClick={() => saveWord(w)}
                              className={`shrink-0 rounded-lg border px-2.5 py-1.5 text-[11px] font-bold transition-colors ${
                                isSaved
                                  ? 'border-emerald-300 bg-emerald-100 text-emerald-700'
                                  : 'border-indigo-300 bg-indigo-600 text-white hover:bg-indigo-700'
                              }`}
                            >
                              {isSaving ? (
                                <Loader2 className="h-3 w-3 animate-spin" />
                              ) : isSaved ? (
                                <>
                                  <Check className="mr-0.5 inline h-3 w-3" /> Đã lưu
                                </>
                              ) : (
                                <>
                                  <Plus className="mr-0.5 inline h-3 w-3" /> Lưu từ
                                </>
                              )}
                            </button>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                )}
              </div>
            )}
          </>
        )}
      </div>
    </StudentShell>
  );
}
