'use client';

import React, { useState } from 'react';
import {
  SplitPaneLayout,
  SpeakingStimulusPane,
  SpeakingInteractionPane,
  type SpeakingStimulusData
} from '@/components/speaking/split-pane';

// Mock STT Hook for demo purposes
const useMockSTT = () => {
  const [isRecording, setIsRecording] = useState(false);
  const [transcript, setTranscript] = useState('');
  
  const startRecording = () => {
    setIsRecording(true);
    setTranscript('');
    let i = 0;
    // Updated phrase to match the "take out money" action
    const phrases = ["I ", "need ", "to ", "take ", "out ", "money ", "from ", "my ", "wallet."];
    
    const interval = setInterval(() => {
      if (i < phrases.length) {
        setTranscript(prev => prev + phrases[i]);
        i++;
      } else {
        clearInterval(interval);
      }
    }, 400);
  };
  
  const stopRecording = () => {
    setIsRecording(false);
  };
  
  return { isRecording, transcript, startRecording, stopRecording };
};

export default function SpeakingDemoPage() {
  const { isRecording, transcript, startRecording, stopRecording } = useMockSTT();

  // Injecting real data enriched by the Teamwork agents
  const mockStimulus: SpeakingStimulusData = {
    titleEn: 'Vocabulary: Wallet',
    titleVi: 'Từ vựng: Cái ví',
    category: 'objects-around-me',
    level: 'A1',
    // REAL Unsplash URL generated by agents
    imageUrl: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'A wallet',
    situationVi: 'Bạn đang muốn lấy tiền ra để trả tiền cafe. Hãy dùng từ Wallet và cụm hành động gợi ý.',
    cueCardBullets: [
      'Pronunciation: /ˈwɒl.ɪt/',
      'Meaning: cái ví',
    ]
  };

  return (
    <div className="w-full h-screen bg-slate-50 dark:bg-slate-950 flex flex-col">
      <header className="h-14 border-b border-slate-200 dark:border-slate-800 flex items-center px-4 shrink-0 bg-white dark:bg-slate-900">
        <h1 className="font-bold text-lg text-slate-800 dark:text-slate-100">LingoPro Speaking: Enriched Data Demo</h1>
      </header>
      
      <div className="flex-1 overflow-hidden">
        <SplitPaneLayout
          ratio="50/50"
          leftPane={
            <div className="p-4 sm:p-6 h-full">
              <SpeakingStimulusPane 
                stimulus={mockStimulus}
                isRecording={isRecording}
              />
            </div>
          }
          rightPane={
            <div className="p-4 sm:p-6 h-full flex flex-col justify-center items-center">
              <div className="w-full max-w-md">
                <SpeakingInteractionPane
                  taskPrompt="Describe what you do with your wallet."
                  hintsVi={[
                    "Hành động: lấy tiền ra (take out money)",
                    "Hành động: cất giữ thẻ an toàn (keep cards safely)",
                    "Hành động: kéo khóa ví lại (zip up the pocket)"
                  ]}
                  suggestedStarters={[
                    "I take out money...",
                    "I keep cards safely...",
                    "I zip up..."
                  ]}
                  recordingState={isRecording ? 'recording' : 'idle'}
                  audioLevel={isRecording ? 0.6 : 0}
                  onStartRecording={startRecording}
                  onStopRecording={stopRecording}
                  interimTranscript={isRecording ? transcript : ''}
                  finalTranscript={!isRecording ? transcript : ''}
                />
              </div>
            </div>
          }
        />
      </div>
    </div>
  );
}
