/**
 * Wordbanks A0–A1 — header + ghi chú Việt hóa đầy đủ.
 * Ví dụ tiếng Anh giữ nguyên để học.
 * Batch 2 (pronouns, modals, future…) → wordbanks-batch2.mjs
 * Batch 3 (A2 perfect/passive/reported…) → wordbanks-batch3.mjs
 */
import { batch2ForSlug } from './wordbanks-batch2.mjs';
import { batch3ForSlug } from './wordbanks-batch3.mjs';

export const UNCOUNTABLE_BANKS = [
{
  title: "U · Đồ ăn / đồ uống (list ôn thi)",
  icon: "🍞",
  note: "Không *a bread / two rices*. Đếm bằng đơn vị: a loaf of bread, a bowl of rice, a cup of tea.",
  rows: [
    { "Từ": "bread", "Nghĩa": "bánh mì", "Sai hay gặp": "a bread · breads", "Cách đúng": "some bread · a loaf/slice of bread" },
    { "Từ": "rice", "Nghĩa": "gạo / cơm", "Sai hay gặp": "a rice · rices", "Cách đúng": "some rice · a bowl of rice" },
    { "Từ": "pasta", "Nghĩa": "mì Ý", "Sai hay gặp": "pastas (khi nói món chung)", "Cách đúng": "some pasta · a plate of pasta" },
    { "Từ": "flour", "Nghĩa": "bột mì", "Sai hay gặp": "a flour", "Cách đúng": "some flour · a bag of flour" },
    { "Từ": "cereal", "Nghĩa": "ngũ cốc", "Sai hay gặp": "a cereal (khi nói chất)", "Cách đúng": "some cereal · a bowl of cereal" },
    { "Từ": "toast", "Nghĩa": "bánh mì nướng", "Sai hay gặp": "a toast", "Cách đúng": "some toast · a slice of toast" },
    { "Từ": "meat", "Nghĩa": "thịt (chung)", "Sai hay gặp": "a meat", "Cách đúng": "some meat · a piece of meat" },
    { "Từ": "beef", "Nghĩa": "thịt bò", "Sai hay gặp": "beefs", "Cách đúng": "some beef" },
    { "Từ": "pork", "Nghĩa": "thịt heo", "Sai hay gặp": "porks", "Cách đúng": "some pork" },
    { "Từ": "lamb", "Nghĩa": "thịt cừu", "Sai hay gặp": "lambs (khi = thịt)", "Cách đúng": "some lamb" },
    { "Từ": "chicken", "Nghĩa": "thịt gà (U)", "Sai hay gặp": "a chicken = con gà (C)", "Cách đúng": "some chicken (thịt) / a chicken (con)" },
    { "Từ": "fish", "Nghĩa": "thịt cá (U)", "Sai hay gặp": "fishes (thịt)", "Cách đúng": "some fish · two fish (con)" },
    { "Từ": "butter", "Nghĩa": "bơ", "Sai hay gặp": "a butter", "Cách đúng": "some butter · a knob of butter" },
    { "Từ": "cheese", "Nghĩa": "phô mai", "Sai hay gặp": "a cheese (khối)", "Cách đúng": "some cheese · a slice/piece of cheese" },
    { "Từ": "jam", "Nghĩa": "mứt", "Sai hay gặp": "a jam", "Cách đúng": "some jam · a jar of jam" },
    { "Từ": "honey", "Nghĩa": "mật ong", "Sai hay gặp": "a honey", "Cách đúng": "some honey" },
    { "Từ": "sugar", "Nghĩa": "đường", "Sai hay gặp": "a sugar · sugars", "Cách đúng": "some sugar · a spoonful of sugar" },
    { "Từ": "salt", "Nghĩa": "muối", "Sai hay gặp": "a salt", "Cách đúng": "some salt · a pinch of salt" },
    { "Từ": "pepper", "Nghĩa": "tiêu", "Sai hay gặp": "a pepper (= quả ớt C)", "Cách đúng": "some pepper (bột)" },
    { "Từ": "oil", "Nghĩa": "dầu", "Sai hay gặp": "an oil", "Cách đúng": "some oil · a bottle of oil" },
    { "Từ": "soup", "Nghĩa": "súp", "Sai hay gặp": "a soup (thường)", "Cách đúng": "some soup · a bowl of soup" },
    { "Từ": "chocolate", "Nghĩa": "sô-cô-la (chất)", "Sai hay gặp": "a chocolate = viên (C)", "Cách đúng": "some chocolate · a bar of chocolate" },
    { "Từ": "ice cream", "Nghĩa": "kem (chất)", "Sai hay gặp": "an ice cream = que/ly (C)", "Cách đúng": "some ice cream · a scoop of…" },
    { "Từ": "food", "Nghĩa": "thức ăn (chung)", "Sai hay gặp": "a food · foods (loại món = C nâng cao)", "Cách đúng": "some food · a lot of food" },
    { "Từ": "fruit", "Nghĩa": "trái cây (chung)", "Sai hay gặp": "fruits (khi nói chung)", "Cách đúng": "some fruit · a piece of fruit" },
    { "Từ": "water", "Nghĩa": "nước", "Sai hay gặp": "a water · two waters", "Cách đúng": "some water · a glass/bottle of water" },
    { "Từ": "milk", "Nghĩa": "sữa", "Sai hay gặp": "a milk", "Cách đúng": "some milk · a carton of milk" },
    { "Từ": "tea", "Nghĩa": "trà", "Sai hay gặp": "a tea = ly (C)", "Cách đúng": "some tea · a cup of tea" },
    { "Từ": "coffee", "Nghĩa": "cà phê", "Sai hay gặp": "a coffee = ly (C)", "Cách đúng": "some coffee · two coffees (ly)" },
    { "Từ": "juice", "Nghĩa": "nước ép", "Sai hay gặp": "a juice", "Cách đúng": "some juice · a glass of juice" },
    { "Từ": "wine", "Nghĩa": "rượu vang", "Sai hay gặp": "a wine", "Cách đúng": "some wine · a glass of wine" },
    { "Từ": "beer", "Nghĩa": "bia", "Sai hay gặp": "a beer = lon/chai (C)", "Cách đúng": "some beer · two beers (lon)" }
  ],
},
{
  title: "U · Trường học / ý niệm (bẫy VN — list thi)",
  icon: "📚",
  note: "VN hay nói “những thông tin / bài tập / lời khuyên” → tiếng Anh **không thêm -s**.",
  rows: [
    { "Từ": "homework", "Nghĩa": "bài tập về nhà", "Sai hay gặp": "homeworks", "Cách đúng": "a lot of homework · some homework" },
    { "Từ": "work", "Nghĩa": "công việc", "Sai hay gặp": "works (≠ tác phẩm)", "Cách đúng": "hard work · a lot of work" },
    { "Từ": "housework", "Nghĩa": "việc nhà", "Sai hay gặp": "houseworks", "Cách đúng": "do the housework" },
    { "Từ": "information", "Nghĩa": "thông tin", "Sai hay gặp": "informations · an information", "Cách đúng": "some information · a piece of information" },
    { "Từ": "advice", "Nghĩa": "lời khuyên", "Sai hay gặp": "advices · an advice", "Cách đúng": "some advice · a piece of advice" },
    { "Từ": "news", "Nghĩa": "tin tức", "Sai hay gặp": "a news · many news", "Cách đúng": "the news is… · some good news" },
    { "Từ": "knowledge", "Nghĩa": "kiến thức", "Sai hay gặp": "knowledges", "Cách đúng": "knowledge of English" },
    { "Từ": "progress", "Nghĩa": "sự tiến bộ", "Sai hay gặp": "progresses (N)", "Cách đúng": "make progress" },
    { "Từ": "research", "Nghĩa": "nghiên cứu", "Sai hay gặp": "researches (N)", "Cách đúng": "do research" },
    { "Từ": "evidence", "Nghĩa": "bằng chứng", "Sai hay gặp": "evidences", "Cách đúng": "some evidence" },
    { "Từ": "vocabulary", "Nghĩa": "từ vựng (chung)", "Sai hay gặp": "vocabularies", "Cách đúng": "learn vocabulary" },
    { "Từ": "grammar", "Nghĩa": "ngữ pháp", "Sai hay gặp": "grammars", "Cách đúng": "study grammar" },
    { "Từ": "music", "Nghĩa": "âm nhạc", "Sai hay gặp": "a music", "Cách đúng": "I like music." },
    { "Từ": "art", "Nghĩa": "nghệ thuật / môn vẽ", "Sai hay gặp": "an art (chung)", "Cách đúng": "study art" },
    { "Từ": "history", "Nghĩa": "lịch sử (môn)", "Sai hay gặp": "a history (chung)", "Cách đúng": "study history" },
    { "Từ": "literature", "Nghĩa": "văn học", "Sai hay gặp": "literatures", "Cách đúng": "study literature" },
    { "Từ": "maths / math", "Nghĩa": "toán", "Sai hay gặp": "a math", "Cách đúng": "study maths" },
    { "Từ": "physics", "Nghĩa": "vật lý", "Sai hay gặp": "a physic", "Cách đúng": "study physics" },
    { "Từ": "chemistry", "Nghĩa": "hóa học", "Sai hay gặp": "a chemistry", "Cách đúng": "study chemistry" },
    { "Từ": "biology", "Nghĩa": "sinh học", "Sai hay gặp": "a biology", "Cách đúng": "study biology" },
    { "Từ": "geography", "Nghĩa": "địa lý", "Sai hay gặp": "a geography", "Cách đúng": "study geography" },
    { "Từ": "English", "Nghĩa": "tiếng Anh (ngôn ngữ)", "Sai hay gặp": "an English (ngôn ngữ)", "Cách đúng": "speak English · study English" },
    { "Từ": "permission", "Nghĩa": "sự cho phép", "Sai hay gặp": "a permission", "Cách đúng": "ask for permission" },
    { "Từ": "experience", "Nghĩa": "kinh nghiệm (U)", "Sai hay gặp": "experiences = trải nghiệm (C)", "Cách đúng": "have experience · an experience" },
    { "Từ": "education", "Nghĩa": "giáo dục", "Sai hay gặp": "an education (đôi khi OK)", "Cách đúng": "get a good education (cố định) · education is…" },
    { "Từ": "health", "Nghĩa": "sức khỏe", "Sai hay gặp": "a health", "Cách đúng": "good health" },
    { "Từ": "help", "Nghĩa": "sự giúp đỡ", "Sai hay gặp": "a help", "Cách đúng": "need help · ask for help" },
    { "Từ": "fun", "Nghĩa": "niềm vui", "Sai hay gặp": "a fun", "Cách đúng": "have fun · It was fun." },
    { "Từ": "luck", "Nghĩa": "may mắn", "Sai hay gặp": "a luck", "Cách đúng": "good luck · some luck" },
    { "Từ": "peace", "Nghĩa": "hòa bình", "Sai hay gặp": "a peace", "Cách đúng": "live in peace" },
    { "Từ": "love", "Nghĩa": "tình yêu", "Sai hay gặp": "a love (chung)", "Cách đúng": "love is…" },
    { "Từ": "happiness", "Nghĩa": "hạnh phúc", "Sai hay gặp": "a happiness", "Cách đúng": "find happiness" },
    { "Từ": "anger", "Nghĩa": "cơn giận", "Sai hay gặp": "an anger", "Cách đúng": "control your anger" },
    { "Từ": "stress", "Nghĩa": "căng thẳng", "Sai hay gặp": "a stress", "Cách đúng": "reduce stress" },
    { "Từ": "beauty", "Nghĩa": "vẻ đẹp", "Sai hay gặp": "a beauty (người = C)", "Cách đúng": "beauty of nature" },
    { "Từ": "freedom", "Nghĩa": "tự do", "Sai hay gặp": "a freedom", "Cách đúng": "fight for freedom" },
    { "Từ": "honesty", "Nghĩa": "sự trung thực", "Sai hay gặp": "an honesty", "Cách đúng": "honesty is important" },
    { "Từ": "success", "Nghĩa": "sự thành công", "Sai hay gặp": "a success (thành tựu = C)", "Cách đúng": "success is… · a success" },
    { "Từ": "failure", "Nghĩa": "sự thất bại (chung)", "Sai hay gặp": "a failure = người/việc (C)", "Cách đúng": "fear of failure" },
    { "Từ": "patience", "Nghĩa": "sự kiên nhẫn", "Sai hay gặp": "a patience", "Cách đúng": "have patience" },
    { "Từ": "courage", "Nghĩa": "lòng dũng cảm", "Sai hay gặp": "a courage", "Cách đúng": "show courage" },
    { "Từ": "confidence", "Nghĩa": "sự tự tin", "Sai hay gặp": "a confidence", "Cách đúng": "build confidence" },
    { "Từ": "intelligence", "Nghĩa": "trí thông minh", "Sai hay gặp": "an intelligence", "Cách đúng": "intelligence matters" },
    { "Từ": "importance", "Nghĩa": "tầm quan trọng", "Sai hay gặp": "an importance", "Cách đúng": "of great importance" },
    { "Từ": "poverty", "Nghĩa": "nghèo đói", "Sai hay gặp": "a poverty", "Cách đúng": "fight poverty" },
    { "Từ": "pollution", "Nghĩa": "ô nhiễm", "Sai hay gặp": "a pollution", "Cách đúng": "reduce pollution" },
    { "Từ": "violence", "Nghĩa": "bạo lực", "Sai hay gặp": "a violence", "Cách đúng": "stop violence" },
    { "Từ": "silence", "Nghĩa": "sự im lặng", "Sai hay gặp": "a silence (đôi khi C)", "Cách đúng": "in silence" },
    { "Từ": "space", "Nghĩa": "không gian (chung)", "Sai hay gặp": "a space = chỗ trống (C)", "Cách đúng": "outer space · no space" },
    { "Từ": "accommodation", "Nghĩa": "chỗ ở", "Sai hay gặp": "an accommodation", "Cách đúng": "find accommodation" },
    { "Từ": "transport / transportation", "Nghĩa": "giao thông vận tải", "Sai hay gặp": "a transport", "Cách đúng": "public transport" },
    { "Từ": "scenery", "Nghĩa": "phong cảnh", "Sai hay gặp": "sceneries", "Cách đúng": "beautiful scenery" },
    { "Từ": "behaviour / behavior", "Nghĩa": "hành vi", "Sai hay gặp": "behaviours (BrE formal)", "Cách đúng": "good behaviour" },
    { "Từ": "gossip", "Nghĩa": "tin đồn", "Sai hay gặp": "a gossip (= người hay ngồi lê)", "Cách đúng": "some gossip" },
    { "Từ": "insurance", "Nghĩa": "bảo hiểm", "Sai hay gặp": "an insurance", "Cách đúng": "buy insurance · an insurance policy" },
    { "Từ": "furniture", "Nghĩa": "đồ đạc", "Sai hay gặp": "furnitures", "Cách đúng": "some furniture · a piece of furniture" }
  ],
},
{
  title: "U · Vật liệu / thiên nhiên / tiền–thời gian / đồ đạc",
  icon: "🌧️",
  note: "Nhóm tài liệu thi hay in dạng bảng dài — học theo **nhóm**, không alphabet mù.",
  rows: [
    { "Nhóm": "Vật liệu", "Từ": "wood", "Nghĩa": "gỗ" },
    { "Nhóm": "Vật liệu", "Từ": "paper", "Nghĩa": "giấy (U) · a paper = báo (C)" },
    { "Nhóm": "Vật liệu", "Từ": "glass", "Nghĩa": "thủy tinh (U) · a glass = cốc (C)" },
    { "Nhóm": "Vật liệu", "Từ": "plastic", "Nghĩa": "nhựa" },
    { "Nhóm": "Vật liệu", "Từ": "metal", "Nghĩa": "kim loại" },
    { "Nhóm": "Vật liệu", "Từ": "gold", "Nghĩa": "vàng" },
    { "Nhóm": "Vật liệu", "Từ": "silver", "Nghĩa": "bạc" },
    { "Nhóm": "Vật liệu", "Từ": "iron", "Nghĩa": "sắt (U) · an iron = bàn ủi (C)" },
    { "Nhóm": "Vật liệu", "Từ": "steel", "Nghĩa": "thép" },
    { "Nhóm": "Vật liệu", "Từ": "cotton", "Nghĩa": "bông" },
    { "Nhóm": "Vật liệu", "Từ": "wool", "Nghĩa": "len" },
    { "Nhóm": "Vật liệu", "Từ": "silk", "Nghĩa": "lụa" },
    { "Nhóm": "Vật liệu", "Từ": "leather", "Nghĩa": "da thuộc" },
    { "Nhóm": "Vật liệu", "Từ": "rubber", "Nghĩa": "cao su" },
    { "Nhóm": "Vật liệu", "Từ": "cement", "Nghĩa": "xi măng" },
    { "Nhóm": "Thiên nhiên", "Từ": "air", "Nghĩa": "không khí" },
    { "Nhóm": "Thiên nhiên", "Từ": "weather", "Nghĩa": "thời tiết" },
    { "Nhóm": "Thiên nhiên", "Từ": "rain", "Nghĩa": "mưa" },
    { "Nhóm": "Thiên nhiên", "Từ": "snow", "Nghĩa": "tuyết" },
    { "Nhóm": "Thiên nhiên", "Từ": "ice", "Nghĩa": "băng" },
    { "Nhóm": "Thiên nhiên", "Từ": "fire", "Nghĩa": "lửa" },
    { "Nhóm": "Thiên nhiên", "Từ": "electricity", "Nghĩa": "điện" },
    { "Nhóm": "Thiên nhiên", "Từ": "energy", "Nghĩa": "năng lượng" },
    { "Nhóm": "Thiên nhiên", "Từ": "light", "Nghĩa": "ánh sáng (U) · lights = đèn (C)" },
    { "Nhóm": "Thiên nhiên", "Từ": "heat", "Nghĩa": "nhiệt" },
    { "Nhóm": "Thiên nhiên", "Từ": "smoke", "Nghĩa": "khói" },
    { "Nhóm": "Thiên nhiên", "Từ": "dust", "Nghĩa": "bụi" },
    { "Nhóm": "Thiên nhiên", "Từ": "sand", "Nghĩa": "cát" },
    { "Nhóm": "Tiền / thời gian", "Từ": "money", "Nghĩa": "tiền" },
    { "Nhóm": "Tiền / thời gian", "Từ": "cash", "Nghĩa": "tiền mặt" },
    { "Nhóm": "Tiền / thời gian", "Từ": "time", "Nghĩa": "thời gian (U) · times = lần (C)" },
    { "Nhóm": "Tiền / thời gian", "Từ": "sleep", "Nghĩa": "giấc ngủ" },
    { "Nhóm": "Tiền / thời gian", "Từ": "traffic", "Nghĩa": "giao thông" },
    { "Nhóm": "Cơ thể", "Từ": "hair", "Nghĩa": "tóc (U) · a hair = sợi (C)" },
    { "Nhóm": "Cơ thể", "Từ": "blood", "Nghĩa": "máu" },
    { "Nhóm": "Cơ thể", "Từ": "skin", "Nghĩa": "da (chung)" },
    { "Nhóm": "Đồ đạc / hành lý", "Từ": "furniture", "Nghĩa": "đồ đạc" },
    { "Nhóm": "Đồ đạc / hành lý", "Từ": "luggage", "Nghĩa": "hành lý (BrE)" },
    { "Nhóm": "Đồ đạc / hành lý", "Từ": "baggage", "Nghĩa": "hành lý (AmE)" },
    { "Nhóm": "Đồ đạc / hành lý", "Từ": "equipment", "Nghĩa": "thiết bị" },
    { "Nhóm": "Đồ đạc / hành lý", "Từ": "software", "Nghĩa": "phần mềm" },
    { "Nhóm": "Đồ đạc / hành lý", "Từ": "hardware", "Nghĩa": "phần cứng" },
    { "Nhóm": "Đồ đạc / hành lý", "Từ": "rubbish / garbage", "Nghĩa": "rác" },
    { "Nhóm": "Đồ đạc / hành lý", "Từ": "trash", "Nghĩa": "rác (AmE)" }
  ],
},
{
  title: "U · Thể thao / bệnh / hoạt động (tài liệu thi hay gài)",
  icon: "⚽",
  note: "play + sport (không mạo từ (zero article)). Nhiều tên bệnh = U + is.",
  rows: [
    { "Nhóm": "Thể thao", "Từ": "football / soccer", "Nghĩa": "bóng đá", "Cách dùng": "play football (không the)" },
    { "Nhóm": "Thể thao", "Từ": "tennis", "Nghĩa": "quần vợt", "Cách dùng": "play tennis" },
    { "Nhóm": "Thể thao", "Từ": "basketball", "Nghĩa": "bóng rổ", "Cách dùng": "play basketball" },
    { "Nhóm": "Thể thao", "Từ": "volleyball", "Nghĩa": "bóng chuyền", "Cách dùng": "play volleyball" },
    { "Nhóm": "Thể thao", "Từ": "badminton", "Nghĩa": "cầu lông", "Cách dùng": "play badminton" },
    { "Nhóm": "Thể thao", "Từ": "chess", "Nghĩa": "cờ vua", "Cách dùng": "play chess" },
    { "Nhóm": "Thể thao", "Từ": "golf", "Nghĩa": "golf", "Cách dùng": "play golf" },
    { "Nhóm": "Bệnh / sức khỏe", "Từ": "flu / influenza", "Nghĩa": "cúm", "Cách dùng": "have the flu (the hay gặp) · flu is…" },
    { "Nhóm": "Bệnh / sức khỏe", "Từ": "cancer", "Nghĩa": "ung thư", "Cách dùng": "cancer is serious" },
    { "Nhóm": "Bệnh / sức khỏe", "Từ": "diabetes", "Nghĩa": "tiểu đường", "Cách dùng": "have diabetes" },
    { "Nhóm": "Bệnh / sức khỏe", "Từ": "measles", "Nghĩa": "sởi", "Cách dùng": "measles is… (U + is)" },
    { "Nhóm": "Bệnh / sức khỏe", "Từ": "mumps", "Nghĩa": "quai bị", "Cách dùng": "mumps is…" },
    { "Nhóm": "Bệnh / sức khỏe", "Từ": "toothache", "Nghĩa": "đau răng", "Cách dùng": "have toothache / a toothache (cả hai)" },
    { "Nhóm": "Bệnh / sức khỏe", "Từ": "headache", "Nghĩa": "đau đầu", "Cách dùng": "have a headache (C!)" },
    { "Nhóm": "Hoạt động", "Từ": "shopping", "Nghĩa": "mua sắm", "Cách dùng": "go shopping · do the shopping" },
    { "Nhóm": "Hoạt động", "Từ": "parking", "Nghĩa": "chỗ đậu xe (chung)", "Cách dùng": "no parking" },
    { "Nhóm": "Hoạt động", "Từ": "training", "Nghĩa": "đào tạo / tập luyện", "Cách dùng": "staff training" },
    { "Nhóm": "Hoạt động", "Từ": "advertising", "Nghĩa": "quảng cáo (lĩnh vực)", "Cách dùng": "work in advertising" }
  ],
},
{
  title: "U · Unitiser (cách “đếm” — tài liệu thi)",
  icon: "📦",
  note: "Học **cụm**: a piece of advice, two bottles of water…",
  rows: [
    { "Đơn vị": "a piece of", "Đi với danh từ U": "advice · information · furniture · cake · paper · news · luggage · equipment" },
    { "Đơn vị": "a bit / a little of", "Đi với danh từ U": "sugar · milk · time · luck · help" },
    { "Đơn vị": "a bottle of", "Đi với danh từ U": "water · milk · juice · oil · wine · beer" },
    { "Đơn vị": "a glass of", "Đi với danh từ U": "water · milk · juice · wine" },
    { "Đơn vị": "a cup of", "Đi với danh từ U": "tea · coffee · soup" },
    { "Đơn vị": "a bowl of", "Đi với danh từ U": "rice · soup · cereal · pasta" },
    { "Đơn vị": "a plate of", "Đi với danh từ U": "rice · pasta · food" },
    { "Đơn vị": "a loaf of", "Đi với danh từ U": "bread" },
    { "Đơn vị": "a slice of", "Đi với danh từ U": "bread · cake · cheese · pizza · toast" },
    { "Đơn vị": "a bar of", "Đi với danh từ U": "chocolate · soap" },
    { "Đơn vị": "a carton of", "Đi với danh từ U": "milk · juice" },
    { "Đơn vị": "a can of", "Đi với danh từ U": "soda · beer · soup" },
    { "Đơn vị": "a jar of", "Đi với danh từ U": "jam · honey · coffee" },
    { "Đơn vị": "a kilo / pack of", "Đi với danh từ U": "rice · sugar · flour" },
    { "Đơn vị": "an item / a piece of", "Đi với danh từ U": "luggage · baggage · equipment · clothing" },
    { "Đơn vị": "a pair of", "Đi với (thường danh từ cặp C)": "scissors · jeans · trousers · glasses · shoes · socks" }
  ],
},
{
  title: "Hai mặt C ⇄ U (cùng chính tả — bẫy đề)",
  icon: "🔀",
  note: "Cùng từ, nghĩa khác → C hoặc U khác. Đề hay gài *chicken / paper / glass / experience*.",
  rows: [
    { "Từ": "chicken", "Đếm được (C)": "a chicken (con gà)", "Không đếm (U)": "chicken (thịt gà)" },
    { "Từ": "fish", "Đếm được (C)": "two fish / fishes (loài)", "Không đếm (U)": "fish (thịt cá)" },
    { "Từ": "coffee", "Đếm được (C)": "two coffees (ly)", "Không đếm (U)": "coffee (chất lỏng chung)" },
    { "Từ": "tea", "Đếm được (C)": "two teas (ly)", "Không đếm (U)": "tea (chất)" },
    { "Từ": "beer", "Đếm được (C)": "two beers (lon/chai)", "Không đếm (U)": "beer (chất)" },
    { "Từ": "paper", "Đếm được (C)": "a paper (báo / bài)", "Không đếm (U)": "paper (giấy)" },
    { "Từ": "glass", "Đếm được (C)": "a glass (cốc)", "Không đếm (U)": "glass (thủy tinh)" },
    { "Từ": "iron", "Đếm được (C)": "an iron (bàn ủi)", "Không đếm (U)": "iron (sắt)" },
    { "Từ": "hair", "Đếm được (C)": "a hair (1 sợi)", "Không đếm (U)": "hair (mái tóc)" },
    { "Từ": "time", "Đếm được (C)": "three times (lần)", "Không đếm (U)": "time (thời gian)" },
    { "Từ": "room", "Đếm được (C)": "two rooms (phòng)", "Không đếm (U)": "room (chỗ trống: no room)" },
    { "Từ": "light", "Đếm được (C)": "lights (đèn)", "Không đếm (U)": "light (ánh sáng)" },
    { "Từ": "experience", "Đếm được (C)": "an experience (trải nghiệm)", "Không đếm (U)": "experience (kinh nghiệm)" },
    { "Từ": "work", "Đếm được (C)": "works (tác phẩm)", "Không đếm (U)": "work (công việc)" },
    { "Từ": "chocolate", "Đếm được (C)": "a chocolate (viên)", "Không đếm (U)": "chocolate (chất)" },
    { "Từ": "ice cream", "Đếm được (C)": "an ice cream (que/ly)", "Không đếm (U)": "ice cream (chất)" },
    { "Từ": "business", "Đếm được (C)": "a business (công ty)", "Không đếm (U)": "business (kinh doanh chung)" },
    { "Từ": "noise", "Đếm được (C)": "a noise (tiếng động cụ thể)", "Không đếm (U)": "noise (tiếng ồn chung)" },
    { "Từ": "life", "Đếm được (C)": "lives (cuộc đời nhiều người)", "Không đếm (U)": "life (cuộc sống chung)" },
    { "Từ": "fire", "Đếm được (C)": "a fire (đám cháy)", "Không đếm (U)": "fire (lửa nói chung)" }
  ],
},
{
  title: "C · Danh từ đếm được hay gặp (đối chiếu)",
  icon: "🔢",
  note: "Có số ít/số nhiều; dùng a/an, many, few, số đếm.",
  rows: [
    { "Từ": "book", "Số nhiều": "books", "Ví dụ": "two books" },
    { "Từ": "pen", "Số nhiều": "pens", "Ví dụ": "a pen" },
    { "Từ": "apple", "Số nhiều": "apples", "Ví dụ": "an apple" },
    { "Từ": "student", "Số nhiều": "students", "Ví dụ": "many students" },
    { "Từ": "teacher", "Số nhiều": "teachers", "Ví dụ": "a teacher" },
    { "Từ": "car", "Số nhiều": "cars", "Ví dụ": "three cars" },
    { "Từ": "house", "Số nhiều": "houses", "Ví dụ": "a house" },
    { "Từ": "chair", "Số nhiều": "chairs", "Ví dụ": "four chairs" },
    { "Từ": "table", "Số nhiều": "tables", "Ví dụ": "a table" },
    { "Từ": "phone", "Số nhiều": "phones", "Ví dụ": "my phone" },
    { "Từ": "bag", "Số nhiều": "bags", "Ví dụ": "two bags" },
    { "Từ": "dog", "Số nhiều": "dogs", "Ví dụ": "a dog" },
    { "Từ": "cat", "Số nhiều": "cats", "Ví dụ": "cats are cute" },
    { "Từ": "egg", "Số nhiều": "eggs", "Ví dụ": "six eggs" },
    { "Từ": "bottle", "Số nhiều": "bottles", "Ví dụ": "a bottle of water" },
    { "Từ": "cup", "Số nhiều": "cups", "Ví dụ": "a cup of tea" },
    { "Từ": "idea", "Số nhiều": "ideas", "Ví dụ": "an idea" },
    { "Từ": "problem", "Số nhiều": "problems", "Ví dụ": "many problems" },
    { "Từ": "question", "Số nhiều": "questions", "Ví dụ": "any questions?" },
    { "Từ": "friend", "Số nhiều": "friends", "Ví dụ": "a few friends" }
  ],
}
];

export const PLURAL_BANKS = [
{
  title: "Có quy tắc · -s / -es / -ies / -ves / -oes (mẫu dài)",
  icon: "📝",
  note: "Học theo **đuôi**. Checklist: bất quy tắc? → sibilant +es → consonant+y → ies → f/fe → ves → còn lại +s.",
  rows: [
    { "Quy tắc": "+ s (thường)", "Số ít": "book", "Số nhiều": "books" },
    { "Quy tắc": "+ s (thường)", "Số ít": "pen", "Số nhiều": "pens" },
    { "Quy tắc": "+ s (thường)", "Số ít": "day", "Số nhiều": "days" },
    { "Quy tắc": "+ s (thường)", "Số ít": "dog", "Số nhiều": "dogs" },
    { "Quy tắc": "+ s (thường)", "Số ít": "cat", "Số nhiều": "cats" },
    { "Quy tắc": "+ s (thường)", "Số ít": "key", "Số nhiều": "keys" },
    { "Quy tắc": "+ s (thường)", "Số ít": "boy", "Số nhiều": "boys" },
    { "Quy tắc": "+ s (thường)", "Số ít": "car", "Số nhiều": "cars" },
    { "Quy tắc": "+ s (thường)", "Số ít": "house", "Số nhiều": "houses" },
    { "Quy tắc": "+ s (thường)", "Số ít": "bag", "Số nhiều": "bags" },
    { "Quy tắc": "+ s (thường)", "Số ít": "phone", "Số nhiều": "phones" },
    { "Quy tắc": "+ s (thường)", "Số ít": "school", "Số nhiều": "schools" },
    { "Quy tắc": "+ es (đuôi s/x/z/ch/sh)", "Số ít": "bus", "Số nhiều": "buses" },
    { "Quy tắc": "+ es (đuôi s/x/z/ch/sh)", "Số ít": "box", "Số nhiều": "boxes" },
    { "Quy tắc": "+ es (đuôi s/x/z/ch/sh)", "Số ít": "watch", "Số nhiều": "watches" },
    { "Quy tắc": "+ es (đuôi s/x/z/ch/sh)", "Số ít": "dish", "Số nhiều": "dishes" },
    { "Quy tắc": "+ es (đuôi s/x/z/ch/sh)", "Số ít": "class", "Số nhiều": "classes" },
    { "Quy tắc": "+ es (đuôi s/x/z/ch/sh)", "Số ít": "glass", "Số nhiều": "glasses" },
    { "Quy tắc": "+ es (đuôi s/x/z/ch/sh)", "Số ít": "brush", "Số nhiều": "brushes" },
    { "Quy tắc": "+ es (đuôi s/x/z/ch/sh)", "Số ít": "match", "Số nhiều": "matches" },
    { "Quy tắc": "+ es (đuôi s/x/z/ch/sh)", "Số ít": "quiz", "Số nhiều": "quizzes" },
    { "Quy tắc": "+ es (đuôi s/x/z/ch/sh)", "Số ít": "fox", "Số nhiều": "foxes" },
    { "Quy tắc": "+ es (đuôi s/x/z/ch/sh)", "Số ít": "church", "Số nhiều": "churches" },
    { "Quy tắc": "+ es (đuôi s/x/z/ch/sh)", "Số ít": "wish", "Số nhiều": "wishes" },
    { "Quy tắc": "phụ âm + y → ies", "Số ít": "city", "Số nhiều": "cities" },
    { "Quy tắc": "phụ âm + y → ies", "Số ít": "baby", "Số nhiều": "babies" },
    { "Quy tắc": "phụ âm + y → ies", "Số ít": "country", "Số nhiều": "countries" },
    { "Quy tắc": "phụ âm + y → ies", "Số ít": "family", "Số nhiều": "families" },
    { "Quy tắc": "phụ âm + y → ies", "Số ít": "party", "Số nhiều": "parties" },
    { "Quy tắc": "phụ âm + y → ies", "Số ít": "story", "Số nhiều": "stories" },
    { "Quy tắc": "phụ âm + y → ies", "Số ít": "lady", "Số nhiều": "ladies" },
    { "Quy tắc": "phụ âm + y → ies", "Số ít": "fly", "Số nhiều": "flies" },
    { "Quy tắc": "phụ âm + y → ies", "Số ít": "study", "Số nhiều": "studies" },
    { "Quy tắc": "phụ âm + y → ies", "Số ít": "dictionary", "Số nhiều": "dictionaries" },
    { "Quy tắc": "nguyên âm + y → ys", "Số ít": "boy", "Số nhiều": "boys" },
    { "Quy tắc": "nguyên âm + y → ys", "Số ít": "toy", "Số nhiều": "toys" },
    { "Quy tắc": "nguyên âm + y → ys", "Số ít": "key", "Số nhiều": "keys" },
    { "Quy tắc": "nguyên âm + y → ys", "Số ít": "day", "Số nhiều": "days" },
    { "Quy tắc": "nguyên âm + y → ys", "Số ít": "way", "Số nhiều": "ways" },
    { "Quy tắc": "nguyên âm + y → ys", "Số ít": "play", "Số nhiều": "plays" },
    { "Quy tắc": "nguyên âm + y → ys", "Số ít": "monkey", "Số nhiều": "monkeys" },
    { "Quy tắc": "nguyên âm + y → ys", "Số ít": "tray", "Số nhiều": "trays" },
    { "Quy tắc": "f/fe → ves", "Số ít": "knife", "Số nhiều": "knives" },
    { "Quy tắc": "f/fe → ves", "Số ít": "wife", "Số nhiều": "wives" },
    { "Quy tắc": "f/fe → ves", "Số ít": "life", "Số nhiều": "lives" },
    { "Quy tắc": "f/fe → ves", "Số ít": "leaf", "Số nhiều": "leaves" },
    { "Quy tắc": "f/fe → ves", "Số ít": "wolf", "Số nhiều": "wolves" },
    { "Quy tắc": "f/fe → ves", "Số ít": "shelf", "Số nhiều": "shelves" },
    { "Quy tắc": "f/fe → ves", "Số ít": "thief", "Số nhiều": "thieves" },
    { "Quy tắc": "f/fe → ves", "Số ít": "half", "Số nhiều": "halves" },
    { "Quy tắc": "f/fe → ves", "Số ít": "loaf", "Số nhiều": "loaves" },
    { "Quy tắc": "f/fe → ves", "Số ít": "calf", "Số nhiều": "calves" },
    { "Quy tắc": "f → chỉ +s (ngoại lệ)", "Số ít": "roof", "Số nhiều": "roofs" },
    { "Quy tắc": "f → chỉ +s (ngoại lệ)", "Số ít": "belief", "Số nhiều": "beliefs" },
    { "Quy tắc": "f → chỉ +s (ngoại lệ)", "Số ít": "chief", "Số nhiều": "chiefs" },
    { "Quy tắc": "f → chỉ +s (ngoại lệ)", "Số ít": "chef", "Số nhiều": "chefs" },
    { "Quy tắc": "f → chỉ +s (ngoại lệ)", "Số ít": "cliff", "Số nhiều": "cliffs" },
    { "Quy tắc": "f → chỉ +s (ngoại lệ)", "Số ít": "proof", "Số nhiều": "proofs" },
    { "Quy tắc": "f → chỉ +s (ngoại lệ)", "Số ít": "safe", "Số nhiều": "safes" },
    { "Quy tắc": "đuôi o → thêm oes", "Số ít": "tomato", "Số nhiều": "tomatoes" },
    { "Quy tắc": "đuôi o → thêm oes", "Số ít": "potato", "Số nhiều": "potatoes" },
    { "Quy tắc": "đuôi o → thêm oes", "Số ít": "hero", "Số nhiều": "heroes" },
    { "Quy tắc": "đuôi o → thêm oes", "Số ít": "echo", "Số nhiều": "echoes" },
    { "Quy tắc": "o → os (ngoại lệ)", "Số ít": "photo", "Số nhiều": "photos" },
    { "Quy tắc": "o → os (ngoại lệ)", "Số ít": "piano", "Số nhiều": "pianos" },
    { "Quy tắc": "o → os (ngoại lệ)", "Số ít": "radio", "Số nhiều": "radios" },
    { "Quy tắc": "o → os (ngoại lệ)", "Số ít": "video", "Số nhiều": "videos" },
    { "Quy tắc": "o → os (ngoại lệ)", "Số ít": "kilo", "Số nhiều": "kilos" },
    { "Quy tắc": "o → os (ngoại lệ)", "Số ít": "zoo", "Số nhiều": "zoos" }
  ],
},
{
  title: "Bất quy tắc · 1 dòng / 1 từ (bắt buộc A0–A1 + thi)",
  icon: "🔄",
  note: "Không viết *childs / mans / foots / sheeps / peoples*.",
  rows: [
    { "Số ít": "man", "Số nhiều": "men", "Ghi nhớ": "người đàn ông" },
    { "Số ít": "woman", "Số nhiều": "women", "Ghi nhớ": "phụ nữ · /ˈwɪmɪn/" },
    { "Số ít": "child", "Số nhiều": "children", "Ghi nhớ": "không viết childs / childrens" },
    { "Số ít": "person", "Số nhiều": "people", "Ghi nhớ": "persons = trang trọng / pháp lý" },
    { "Số ít": "foot", "Số nhiều": "feet", "Ghi nhớ": "bàn chân" },
    { "Số ít": "tooth", "Số nhiều": "teeth", "Ghi nhớ": "răng" },
    { "Số ít": "goose", "Số nhiều": "geese", "Ghi nhớ": "ngỗng" },
    { "Số ít": "mouse", "Số nhiều": "mice", "Ghi nhớ": "chuột" },
    { "Số ít": "louse", "Số nhiều": "lice", "Ghi nhớ": "chấy (ít A0)" },
    { "Số ít": "ox", "Số nhiều": "oxen", "Ghi nhớ": "bò đực (hiếm A0)" },
    { "Số ít": "sheep", "Số nhiều": "sheep", "Ghi nhớ": "số nhiều không đổi (zero plural)" },
    { "Số ít": "deer", "Số nhiều": "deer", "Ghi nhớ": "số nhiều không đổi (zero plural)" },
    { "Số ít": "fish", "Số nhiều": "fish / fishes", "Ghi nhớ": "fish = con; fishes = các loài" },
    { "Số ít": "salmon", "Số nhiều": "salmon", "Ghi nhớ": "số nhiều không đổi (thường)" },
    { "Số ít": "trout", "Số nhiều": "trout", "Ghi nhớ": "số nhiều không đổi (thường)" },
    { "Số ít": "moose", "Số nhiều": "moose", "Ghi nhớ": "số nhiều không đổi" },
    { "Số ít": "swine", "Số nhiều": "swine", "Ghi nhớ": "số nhiều không đổi" },
    { "Số ít": "buffalo", "Số nhiều": "buffalo / buffaloes", "Ghi nhớ": "không đổi hoặc +es" },
    { "Số ít": "shrimp", "Số nhiều": "shrimp / shrimps", "Ghi nhớ": "thường không đổi số nhiều" },
    { "Số ít": "aircraft", "Số nhiều": "aircraft", "Ghi nhớ": "số nhiều không đổi" },
    { "Số ít": "spacecraft", "Số nhiều": "spacecraft", "Ghi nhớ": "số nhiều không đổi" },
    { "Số ít": "watercraft", "Số nhiều": "watercraft", "Ghi nhớ": "số nhiều không đổi" },
    { "Số ít": "hovercraft", "Số nhiều": "hovercraft", "Ghi nhớ": "số nhiều không đổi" },
    { "Số ít": "series", "Số nhiều": "series", "Ghi nhớ": "số nhiều không đổi" },
    { "Số ít": "species", "Số nhiều": "species", "Ghi nhớ": "số nhiều không đổi" },
    { "Số ít": "means", "Số nhiều": "means", "Ghi nhớ": "a means of… (một phương tiện…)" },
    { "Số ít": "die", "Số nhiều": "dice", "Ghi nhớ": "xúc xắc (dies = khuôn đúc)" },
    { "Số ít": "penny", "Số nhiều": "pence / pennies", "Ghi nhớ": "pence = giá trị; pennies = đồng xu" },
    { "Số ít": "analysis", "Số nhiều": "analyses", "Ghi nhớ": "Latin/Hy Lạp (A1–A2)" },
    { "Số ít": "crisis", "Số nhiều": "crises", "Ghi nhớ": "Latin/Hy Lạp" },
    { "Số ít": "thesis", "Số nhiều": "theses", "Ghi nhớ": "Latin/Hy Lạp" },
    { "Số ít": "basis", "Số nhiều": "bases", "Ghi nhớ": "Latin/Hy Lạp" },
    { "Số ít": "axis", "Số nhiều": "axes", "Ghi nhớ": "trục" },
    { "Số ít": "criterion", "Số nhiều": "criteria", "Ghi nhớ": "criteria = số nhiều" },
    { "Số ít": "phenomenon", "Số nhiều": "phenomena", "Ghi nhớ": "phenomena = số nhiều" },
    { "Số ít": "datum", "Số nhiều": "data", "Ghi nhớ": "data thường không đếm / số nhiều" },
    { "Số ít": "medium", "Số nhiều": "phương tiện truyền thông (số nhiều)", "Ghi nhớ": "phương tiện truyền thông (số nhiều)" },
    { "Số ít": "index", "Số nhiều": "indices / indexes", "Ghi nhớ": "cả hai đều được" },
    { "Số ít": "appendix", "Số nhiều": "appendices / appendixes", "Ghi nhớ": "phụ lục" },
    { "Số ít": "formula", "Số nhiều": "formulae / formulas", "Ghi nhớ": "công thức" },
    { "Số ít": "cactus", "Số nhiều": "cacti / cactuses", "Ghi nhớ": "xương rồng" },
    { "Số ít": "fungus", "Số nhiều": "fungi", "Ghi nhớ": "nấm" },
    { "Số ít": "nucleus", "Số nhiều": "nuclei", "Ghi nhớ": "hạt nhân" },
    { "Số ít": "focus", "Số nhiều": "foci / focuses", "Ghi nhớ": "tiêu điểm" },
    { "Số ít": "radius", "Số nhiều": "radii / radiuses", "Ghi nhớ": "bán kính" },
    { "Số ít": "alumnus", "Số nhiều": "alumni", "Ghi nhớ": "cựu sinh viên (nam)" },
    { "Số ít": "octopus", "Số nhiều": "octopuses / octopi", "Ghi nhớ": "bạch tuộc" },
    { "Số ít": "syllabus", "Số nhiều": "syllabi / syllabuses", "Ghi nhớ": "đề cương" },
    { "Số ít": "torpedo", "Số nhiều": "torpedoes", "Ghi nhớ": "đuôi o → thêm oes" },
    { "Số ít": "veto", "Số nhiều": "vetoes", "Ghi nhớ": "đuôi o → thêm oes" },
    { "Số ít": "số nhiều không đổi", "Số nhiều": "zeros / zeroes", "Ghi nhớ": "cả hai đều được" }
  ],
},
{
  title: "Luôn số nhiều (plural-only) · a pair of…",
  icon: "👖",
  note: "Đếm “1 cái” → **a pair of**. Động từ thường chia số nhiều: These scissors are…",
  rows: [
    { "Từ": "scissors", "Cách đếm": "a pair of scissors", "Ghi chú": "kéo" },
    { "Từ": "trousers", "Cách đếm": "a pair of trousers", "Ghi chú": "quần (Anh)" },
    { "Từ": "pants", "Cách đếm": "a pair of pants", "Ghi chú": "quần (Mỹ)" },
    { "Từ": "jeans", "Cách đếm": "a pair of jeans", "Ghi chú": "quần jean" },
    { "Từ": "shorts", "Cách đếm": "a pair of shorts", "Ghi chú": "quần short" },
    { "Từ": "glasses", "Cách đếm": "a pair of glasses", "Ghi chú": "kính mắt" },
    { "Từ": "spectacles", "Cách đếm": "a pair of spectacles", "Ghi chú": "kính (trang trọng)" },
    { "Từ": "headphones", "Cách đếm": "a pair of headphones", "Ghi chú": "tai nghe" },
    { "Từ": "earphones", "Cách đếm": "a pair of earphones", "Ghi chú": "tai nghe nhét tai" },
    { "Từ": "shoes", "Cách đếm": "a pair of shoes", "Ghi chú": "giày" },
    { "Từ": "socks", "Cách đếm": "a pair of socks", "Ghi chú": "tất" },
    { "Từ": "gloves", "Cách đếm": "a pair of gloves", "Ghi chú": "găng tay" },
    { "Từ": "clothes", "Cách đếm": "some clothes · an item of clothing", "Ghi chú": "không dùng a clothes" },
    { "Từ": "police", "Cách đếm": "the police are… · a police officer", "Ghi chú": "số nhiều" },
    { "Từ": "people", "Cách đếm": "many people", "Ghi chú": "không peoples (trừ nghĩa dân tộc)" }
  ],
}
];

export const IRREGULAR_PAST_BANK = {
  title: "Động từ bất quy tắc · V1–V2–V3 hay gặp (tài liệu THCS)",
  icon: "⚡",
  note: "Quá khứ đơn khẳng định = **V2**. Phủ định/hỏi: did/didn't + **V1**. Học theo cụm nghĩa, không học A→Z mù.",
  rows: [
    { "V1 (nguyên mẫu)": "be", "V2 (quá khứ)": "was/were", "V3 (phân từ)": "been", "Nghĩa": "thì / là / ở" },
    { "V1 (nguyên mẫu)": "become", "V2 (quá khứ)": "became", "V3 (phân từ)": "become", "Nghĩa": "trở thành" },
    { "V1 (nguyên mẫu)": "begin", "V2 (quá khứ)": "began", "V3 (phân từ)": "begun", "Nghĩa": "bắt đầu" },
    { "V1 (nguyên mẫu)": "break", "V2 (quá khứ)": "broke", "V3 (phân từ)": "broken", "Nghĩa": "làm vỡ" },
    { "V1 (nguyên mẫu)": "bring", "V2 (quá khứ)": "brought", "V3 (phân từ)": "brought", "Nghĩa": "mang đến" },
    { "V1 (nguyên mẫu)": "build", "V2 (quá khứ)": "built", "V3 (phân từ)": "built", "Nghĩa": "xây" },
    { "V1 (nguyên mẫu)": "buy", "V2 (quá khứ)": "bought", "V3 (phân từ)": "bought", "Nghĩa": "mua" },
    { "V1 (nguyên mẫu)": "catch", "V2 (quá khứ)": "caught", "V3 (phân từ)": "caught", "Nghĩa": "bắt" },
    { "V1 (nguyên mẫu)": "choose", "V2 (quá khứ)": "chose", "V3 (phân từ)": "chosen", "Nghĩa": "chọn" },
    { "V1 (nguyên mẫu)": "come", "V2 (quá khứ)": "came", "V3 (phân từ)": "come", "Nghĩa": "đến" },
    { "V1 (nguyên mẫu)": "cost", "V2 (quá khứ)": "cost", "V3 (phân từ)": "cost", "Nghĩa": "có giá" },
    { "V1 (nguyên mẫu)": "cut", "V2 (quá khứ)": "cut", "V3 (phân từ)": "cut", "Nghĩa": "cắt" },
    { "V1 (nguyên mẫu)": "do", "V2 (quá khứ)": "did", "V3 (phân từ)": "done", "Nghĩa": "làm" },
    { "V1 (nguyên mẫu)": "draw", "V2 (quá khứ)": "drew", "V3 (phân từ)": "drawn", "Nghĩa": "vẽ" },
    { "V1 (nguyên mẫu)": "drink", "V2 (quá khứ)": "drank", "V3 (phân từ)": "drunk", "Nghĩa": "uống" },
    { "V1 (nguyên mẫu)": "drive", "V2 (quá khứ)": "drove", "V3 (phân từ)": "driven", "Nghĩa": "lái" },
    { "V1 (nguyên mẫu)": "eat", "V2 (quá khứ)": "ate", "V3 (phân từ)": "eaten", "Nghĩa": "ăn" },
    { "V1 (nguyên mẫu)": "fall", "V2 (quá khứ)": "fell", "V3 (phân từ)": "fallen", "Nghĩa": "ngã / rơi" },
    { "V1 (nguyên mẫu)": "feel", "V2 (quá khứ)": "felt", "V3 (phân từ)": "felt", "Nghĩa": "cảm thấy" },
    { "V1 (nguyên mẫu)": "find", "V2 (quá khứ)": "found", "V3 (phân từ)": "found", "Nghĩa": "tìm thấy" },
    { "V1 (nguyên mẫu)": "fly", "V2 (quá khứ)": "flew", "V3 (phân từ)": "flown", "Nghĩa": "bay" },
    { "V1 (nguyên mẫu)": "forget", "V2 (quá khứ)": "forgot", "V3 (phân từ)": "forgotten", "Nghĩa": "quên" },
    { "V1 (nguyên mẫu)": "get", "V2 (quá khứ)": "got", "V3 (phân từ)": "got/gotten", "Nghĩa": "nhận / trở nên" },
    { "V1 (nguyên mẫu)": "give", "V2 (quá khứ)": "gave", "V3 (phân từ)": "given", "Nghĩa": "cho" },
    { "V1 (nguyên mẫu)": "go", "V2 (quá khứ)": "went", "V3 (phân từ)": "gone", "Nghĩa": "đi" },
    { "V1 (nguyên mẫu)": "grow", "V2 (quá khứ)": "grew", "V3 (phân từ)": "grown", "Nghĩa": "lớn / trồng" },
    { "V1 (nguyên mẫu)": "have", "V2 (quá khứ)": "had", "V3 (phân từ)": "had", "Nghĩa": "có" },
    { "V1 (nguyên mẫu)": "hear", "V2 (quá khứ)": "heard", "V3 (phân từ)": "heard", "Nghĩa": "nghe" },
    { "V1 (nguyên mẫu)": "hide", "V2 (quá khứ)": "hid", "V3 (phân từ)": "hidden", "Nghĩa": "trốn / giấu" },
    { "V1 (nguyên mẫu)": "hit", "V2 (quá khứ)": "hit", "V3 (phân từ)": "hit", "Nghĩa": "đánh / va" },
    { "V1 (nguyên mẫu)": "hold", "V2 (quá khứ)": "held", "V3 (phân từ)": "held", "Nghĩa": "cầm / giữ" },
    { "V1 (nguyên mẫu)": "hurt", "V2 (quá khứ)": "hurt", "V3 (phân từ)": "hurt", "Nghĩa": "làm đau" },
    { "V1 (nguyên mẫu)": "keep", "V2 (quá khứ)": "kept", "V3 (phân từ)": "kept", "Nghĩa": "giữ" },
    { "V1 (nguyên mẫu)": "know", "V2 (quá khứ)": "knew", "V3 (phân từ)": "known", "Nghĩa": "biết" },
    { "V1 (nguyên mẫu)": "leave", "V2 (quá khứ)": "left", "V3 (phân từ)": "left", "Nghĩa": "rời / để lại" },
    { "V1 (nguyên mẫu)": "lend", "V2 (quá khứ)": "lent", "V3 (phân từ)": "lent", "Nghĩa": "cho mượn" },
    { "V1 (nguyên mẫu)": "let", "V2 (quá khứ)": "let", "V3 (phân từ)": "let", "Nghĩa": "để / cho phép" },
    { "V1 (nguyên mẫu)": "lie", "V2 (quá khứ)": "lay", "V3 (phân từ)": "lain", "Nghĩa": "nằm" },
    { "V1 (nguyên mẫu)": "lose", "V2 (quá khứ)": "lost", "V3 (phân từ)": "lost", "Nghĩa": "mất / thua" },
    { "V1 (nguyên mẫu)": "make", "V2 (quá khứ)": "made", "V3 (phân từ)": "made", "Nghĩa": "làm / tạo" },
    { "V1 (nguyên mẫu)": "mean", "V2 (quá khứ)": "meant", "V3 (phân từ)": "meant", "Nghĩa": "có nghĩa" },
    { "V1 (nguyên mẫu)": "meet", "V2 (quá khứ)": "met", "V3 (phân từ)": "met", "Nghĩa": "gặp" },
    { "V1 (nguyên mẫu)": "pay", "V2 (quá khứ)": "paid", "V3 (phân từ)": "paid", "Nghĩa": "trả tiền" },
    { "V1 (nguyên mẫu)": "put", "V2 (quá khứ)": "put", "V3 (phân từ)": "put", "Nghĩa": "đặt" },
    { "V1 (nguyên mẫu)": "read", "V2 (quá khứ)": "read", "V3 (phân từ)": "read", "Nghĩa": "đọc (phát âm khác)" },
    { "V1 (nguyên mẫu)": "ride", "V2 (quá khứ)": "rode", "V3 (phân từ)": "ridden", "Nghĩa": "cưỡi / đi xe" },
    { "V1 (nguyên mẫu)": "ring", "V2 (quá khứ)": "rang", "V3 (phân từ)": "rung", "Nghĩa": "reo chuông" },
    { "V1 (nguyên mẫu)": "rise", "V2 (quá khứ)": "rose", "V3 (phân từ)": "risen", "Nghĩa": "mọc / tăng" },
    { "V1 (nguyên mẫu)": "run", "V2 (quá khứ)": "ran", "V3 (phân từ)": "run", "Nghĩa": "chạy" },
    { "V1 (nguyên mẫu)": "say", "V2 (quá khứ)": "said", "V3 (phân từ)": "said", "Nghĩa": "nói" },
    { "V1 (nguyên mẫu)": "see", "V2 (quá khứ)": "saw", "V3 (phân từ)": "seen", "Nghĩa": "thấy" },
    { "V1 (nguyên mẫu)": "sell", "V2 (quá khứ)": "sold", "V3 (phân từ)": "sold", "Nghĩa": "bán" },
    { "V1 (nguyên mẫu)": "send", "V2 (quá khứ)": "sent", "V3 (phân từ)": "sent", "Nghĩa": "gửi" },
    { "V1 (nguyên mẫu)": "set", "V2 (quá khứ)": "set", "V3 (phân từ)": "set", "Nghĩa": "đặt / cài" },
    { "V1 (nguyên mẫu)": "shake", "V2 (quá khứ)": "shook", "V3 (phân từ)": "shaken", "Nghĩa": "lắc" },
    { "V1 (nguyên mẫu)": "shine", "V2 (quá khứ)": "shone", "V3 (phân từ)": "shone", "Nghĩa": "chiếu sáng" },
    { "V1 (nguyên mẫu)": "shoot", "V2 (quá khứ)": "shot", "V3 (phân từ)": "shot", "Nghĩa": "bắn" },
    { "V1 (nguyên mẫu)": "show", "V2 (quá khứ)": "showed", "V3 (phân từ)": "shown", "Nghĩa": "cho xem" },
    { "V1 (nguyên mẫu)": "shut", "V2 (quá khứ)": "shut", "V3 (phân từ)": "shut", "Nghĩa": "đóng" },
    { "V1 (nguyên mẫu)": "sing", "V2 (quá khứ)": "sang", "V3 (phân từ)": "sung", "Nghĩa": "hát" },
    { "V1 (nguyên mẫu)": "sit", "V2 (quá khứ)": "sat", "V3 (phân từ)": "sat", "Nghĩa": "ngồi" },
    { "V1 (nguyên mẫu)": "sleep", "V2 (quá khứ)": "slept", "V3 (phân từ)": "slept", "Nghĩa": "ngủ" },
    { "V1 (nguyên mẫu)": "speak", "V2 (quá khứ)": "spoke", "V3 (phân từ)": "spoken", "Nghĩa": "nói" },
    { "V1 (nguyên mẫu)": "spend", "V2 (quá khứ)": "spent", "V3 (phân từ)": "spent", "Nghĩa": "tiêu / dành" },
    { "V1 (nguyên mẫu)": "stand", "V2 (quá khứ)": "stood", "V3 (phân từ)": "stood", "Nghĩa": "đứng" },
    { "V1 (nguyên mẫu)": "steal", "V2 (quá khứ)": "stole", "V3 (phân từ)": "stolen", "Nghĩa": "ăn cắp" },
    { "V1 (nguyên mẫu)": "swim", "V2 (quá khứ)": "swam", "V3 (phân từ)": "swum", "Nghĩa": "bơi" },
    { "V1 (nguyên mẫu)": "take", "V2 (quá khứ)": "took", "V3 (phân từ)": "taken", "Nghĩa": "lấy" },
    { "V1 (nguyên mẫu)": "teach", "V2 (quá khứ)": "taught", "V3 (phân từ)": "taught", "Nghĩa": "dạy" },
    { "V1 (nguyên mẫu)": "tell", "V2 (quá khứ)": "told", "V3 (phân từ)": "told", "Nghĩa": "kể / bảo" },
    { "V1 (nguyên mẫu)": "think", "V2 (quá khứ)": "thought", "V3 (phân từ)": "thought", "Nghĩa": "nghĩ" },
    { "V1 (nguyên mẫu)": "throw", "V2 (quá khứ)": "threw", "V3 (phân từ)": "thrown", "Nghĩa": "ném" },
    { "V1 (nguyên mẫu)": "understand", "V2 (quá khứ)": "understood", "V3 (phân từ)": "understood", "Nghĩa": "hiểu" },
    { "V1 (nguyên mẫu)": "wake", "V2 (quá khứ)": "woke", "V3 (phân từ)": "woken", "Nghĩa": "thức dậy" },
    { "V1 (nguyên mẫu)": "wear", "V2 (quá khứ)": "wore", "V3 (phân từ)": "worn", "Nghĩa": "mặc / đeo" },
    { "V1 (nguyên mẫu)": "win", "V2 (quá khứ)": "won", "V3 (phân từ)": "won", "Nghĩa": "thắng" },
    { "V1 (nguyên mẫu)": "write", "V2 (quá khứ)": "wrote", "V3 (phân từ)": "written", "Nghĩa": "viết" },
    { "V1 (nguyên mẫu)": "quit", "V2 (quá khứ)": "quit", "V3 (phân từ)": "quit", "Nghĩa": "bỏ / nghỉ" },
    { "V1 (nguyên mẫu)": "spread", "V2 (quá khứ)": "spread", "V3 (phân từ)": "spread", "Nghĩa": "lan / trải" },
    { "V1 (nguyên mẫu)": "bet", "V2 (quá khứ)": "bet", "V3 (phân từ)": "bet", "Nghĩa": "cá cược" },
    { "V1 (nguyên mẫu)": "broadcast", "V2 (quá khứ)": "broadcast", "V3 (phân từ)": "broadcast", "Nghĩa": "phát sóng" },
    { "V1 (nguyên mẫu)": "arise", "V2 (quá khứ)": "arose", "V3 (phân từ)": "arisen", "Nghĩa": "phát sinh" },
    { "V1 (nguyên mẫu)": "awake", "V2 (quá khứ)": "awoke", "V3 (phân từ)": "awoken", "Nghĩa": "thức giấc" },
    { "V1 (nguyên mẫu)": "bear", "V2 (quá khứ)": "bore", "V3 (phân từ)": "born/borne", "Nghĩa": "chịu / sinh" },
    { "V1 (nguyên mẫu)": "beat", "V2 (quá khứ)": "beat", "V3 (phân từ)": "beaten", "Nghĩa": "đánh bại" },
    { "V1 (nguyên mẫu)": "bend", "V2 (quá khứ)": "bent", "V3 (phân từ)": "bent", "Nghĩa": "uốn / cúi" },
    { "V1 (nguyên mẫu)": "bite", "V2 (quá khứ)": "bit", "V3 (phân từ)": "bitten", "Nghĩa": "cắn" },
    { "V1 (nguyên mẫu)": "bleed", "V2 (quá khứ)": "bled", "V3 (phân từ)": "bled", "Nghĩa": "chảy máu" },
    { "V1 (nguyên mẫu)": "blow", "V2 (quá khứ)": "blew", "V3 (phân từ)": "blown", "Nghĩa": "thổi" },
    { "V1 (nguyên mẫu)": "breed", "V2 (quá khứ)": "bred", "V3 (phân từ)": "bred", "Nghĩa": "nuôi / sinh sản" },
    { "V1 (nguyên mẫu)": "burn", "V2 (quá khứ)": "burnt/burned", "V3 (phân từ)": "burnt/burned", "Nghĩa": "đốt / cháy" },
    { "V1 (nguyên mẫu)": "burst", "V2 (quá khứ)": "burst", "V3 (phân từ)": "burst", "Nghĩa": "nổ / vỡ" },
    { "V1 (nguyên mẫu)": "cast", "V2 (quá khứ)": "cast", "V3 (phân từ)": "cast", "Nghĩa": "ném / đúc" },
    { "V1 (nguyên mẫu)": "cling", "V2 (quá khứ)": "clung", "V3 (phân từ)": "clung", "Nghĩa": "bám" },
    { "V1 (nguyên mẫu)": "creep", "V2 (quá khứ)": "crept", "V3 (phân từ)": "crept", "Nghĩa": "bò / len lỏi" },
    { "V1 (nguyên mẫu)": "deal", "V2 (quá khứ)": "dealt", "V3 (phân từ)": "dealt", "Nghĩa": "xử lý / chia bài" },
    { "V1 (nguyên mẫu)": "dig", "V2 (quá khứ)": "dug", "V3 (phân từ)": "dug", "Nghĩa": "đào" },
    { "V1 (nguyên mẫu)": "dream", "V2 (quá khứ)": "dreamt/dreamed", "V3 (phân từ)": "dreamt/dreamed", "Nghĩa": "mơ" },
    { "V1 (nguyên mẫu)": "feed", "V2 (quá khứ)": "fed", "V3 (phân từ)": "fed", "Nghĩa": "cho ăn" },
    { "V1 (nguyên mẫu)": "fight", "V2 (quá khứ)": "fought", "V3 (phân từ)": "fought", "Nghĩa": "chiến đấu" },
    { "V1 (nguyên mẫu)": "flee", "V2 (quá khứ)": "fled", "V3 (phân từ)": "fled", "Nghĩa": "chạy trốn" },
    { "V1 (nguyên mẫu)": "forbid", "V2 (quá khứ)": "forbade", "V3 (phân từ)": "forbidden", "Nghĩa": "cấm" },
    { "V1 (nguyên mẫu)": "forgive", "V2 (quá khứ)": "forgave", "V3 (phân từ)": "forgiven", "Nghĩa": "tha thứ" },
    { "V1 (nguyên mẫu)": "freeze", "V2 (quá khứ)": "froze", "V3 (phân từ)": "frozen", "Nghĩa": "đóng băng" },
    { "V1 (nguyên mẫu)": "hang", "V2 (quá khứ)": "hung", "V3 (phân từ)": "hung", "Nghĩa": "treo" },
    { "V1 (nguyên mẫu)": "kneel", "V2 (quá khứ)": "knelt/kneeled", "V3 (phân từ)": "knelt/kneeled", "Nghĩa": "quỳ" },
    { "V1 (nguyên mẫu)": "lead", "V2 (quá khứ)": "led", "V3 (phân từ)": "led", "Nghĩa": "dẫn dắt" },
    { "V1 (nguyên mẫu)": "learn", "V2 (quá khứ)": "learnt/learned", "V3 (phân từ)": "learnt/learned", "Nghĩa": "học" },
    { "V1 (nguyên mẫu)": "light", "V2 (quá khứ)": "lit/lighted", "V3 (phân từ)": "lit/lighted", "Nghĩa": "thắp / đốt" },
    { "V1 (nguyên mẫu)": "mistake", "V2 (quá khứ)": "mistook", "V3 (phân từ)": "mistaken", "Nghĩa": "nhầm" },
    { "V1 (nguyên mẫu)": "prove", "V2 (quá khứ)": "proved", "V3 (phân từ)": "proven/proved", "Nghĩa": "chứng minh" },
    { "V1 (nguyên mẫu)": "seek", "V2 (quá khứ)": "sought", "V3 (phân từ)": "sought", "Nghĩa": "tìm kiếm" },
    { "V1 (nguyên mẫu)": "sew", "V2 (quá khứ)": "sewed", "V3 (phân từ)": "sewn/sewed", "Nghĩa": "may" },
    { "V1 (nguyên mẫu)": "sink", "V2 (quá khứ)": "sank", "V3 (phân từ)": "sunk", "Nghĩa": "chìm" },
    { "V1 (nguyên mẫu)": "slide", "V2 (quá khứ)": "slid", "V3 (phân từ)": "slid", "Nghĩa": "trượt" },
    { "V1 (nguyên mẫu)": "smell", "V2 (quá khứ)": "smelt/smelled", "V3 (phân từ)": "smelt/smelled", "Nghĩa": "ngửi / có mùi" },
    { "V1 (nguyên mẫu)": "spell", "V2 (quá khứ)": "spelt/spelled", "V3 (phân từ)": "spelt/spelled", "Nghĩa": "đánh vần" },
    { "V1 (nguyên mẫu)": "spill", "V2 (quá khứ)": "spilt/spilled", "V3 (phân từ)": "spilt/spilled", "Nghĩa": "làm đổ" },
    { "V1 (nguyên mẫu)": "spin", "V2 (quá khứ)": "spun", "V3 (phân từ)": "spun", "Nghĩa": "quay" },
    { "V1 (nguyên mẫu)": "spit", "V2 (quá khứ)": "spat/spit", "V3 (phân từ)": "spat/spit", "Nghĩa": "khạc" },
    { "V1 (nguyên mẫu)": "split", "V2 (quá khứ)": "split", "V3 (phân từ)": "split", "Nghĩa": "tách / chẻ" },
    { "V1 (nguyên mẫu)": "spoil", "V2 (quá khứ)": "spoilt/spoiled", "V3 (phân từ)": "spoilt/spoiled", "Nghĩa": "làm hỏng" },
    { "V1 (nguyên mẫu)": "spring", "V2 (quá khứ)": "sprang", "V3 (phân từ)": "sprung", "Nghĩa": "nhảy vọt" },
    { "V1 (nguyên mẫu)": "stick", "V2 (quá khứ)": "stuck", "V3 (phân từ)": "stuck", "Nghĩa": "dán / kẹt" },
    { "V1 (nguyên mẫu)": "sting", "V2 (quá khứ)": "stung", "V3 (phân từ)": "stung", "Nghĩa": "chích" },
    { "V1 (nguyên mẫu)": "strike", "V2 (quá khứ)": "struck", "V3 (phân từ)": "struck", "Nghĩa": "đánh / đình công" },
    { "V1 (nguyên mẫu)": "swear", "V2 (quá khứ)": "swore", "V3 (phân từ)": "sworn", "Nghĩa": "thề / chửi" },
    { "V1 (nguyên mẫu)": "sweep", "V2 (quá khứ)": "swept", "V3 (phân từ)": "swept", "Nghĩa": "quét" },
    { "V1 (nguyên mẫu)": "swing", "V2 (quá khứ)": "swung", "V3 (phân từ)": "swung", "Nghĩa": "đu / vung" },
    { "V1 (nguyên mẫu)": "tear", "V2 (quá khứ)": "tore", "V3 (phân từ)": "torn", "Nghĩa": "xé" },
    { "V1 (nguyên mẫu)": "weep", "V2 (quá khứ)": "wept", "V3 (phân từ)": "wept", "Nghĩa": "khóc" },
    { "V1 (nguyên mẫu)": "wet", "V2 (quá khứ)": "wet/wetted", "V3 (phân từ)": "wet/wetted", "Nghĩa": "làm ướt" },
    { "V1 (nguyên mẫu)": "wind", "V2 (quá khứ)": "wound", "V3 (phân từ)": "wound", "Nghĩa": "quấn / gió (V)" }
  ],
};

export const ARTICLE_BANKS = [
{
  title: "a / an theo ÂM (không theo chữ cái)",
  icon: "🔊",
  note: "a + phụ âm (âm) · an + nguyên âm (âm). *university* /j/ → a; *hour* silent h → an.",
  rows: [
    { "Mạo từ": "a", "Từ": "book", "Âm đầu": "/b/", "Ghi chú": "phụ âm" },
    { "Mạo từ": "a", "Từ": "cat", "Âm đầu": "/k/", "Ghi chú": "phụ âm" },
    { "Mạo từ": "a", "Từ": "dog", "Âm đầu": "/d/", "Ghi chú": "phụ âm" },
    { "Mạo từ": "a", "Từ": "university", "Âm đầu": "/juː/", "Ghi chú": "âm /j/ = tính phụ âm" },
    { "Mạo từ": "a", "Từ": "European", "Âm đầu": "/j/", "Ghi chú": "European country (nước châu Âu)" },
    { "Mạo từ": "a", "Từ": "one-way street", "Âm đầu": "/w/", "Ghi chú": "one đọc /wʌn/" },
    { "Mạo từ": "a", "Từ": "useful book", "Âm đầu": "/juː/", "Ghi chú": "useful (hữu ích)" },
    { "Mạo từ": "an", "Từ": "apple", "Âm đầu": "/æ/", "Ghi chú": "nguyên âm" },
    { "Mạo từ": "an", "Từ": "egg", "Âm đầu": "/e/", "Ghi chú": "nguyên âm" },
    { "Mạo từ": "an", "Từ": "hour", "Âm đầu": "/aʊ/", "Ghi chú": "h câm" },
    { "Mạo từ": "an", "Từ": "honest man", "Âm đầu": "/ɒ/", "Ghi chú": "h câm" },
    { "Mạo từ": "an", "Từ": "MBA", "Âm đầu": "/em/", "Ghi chú": "chữ M đọc /em/" },
    { "Mạo từ": "an", "Từ": "SOS", "Âm đầu": "/es/", "Ghi chú": "chữ S" },
    { "Mạo từ": "an", "Từ": "umbrella", "Âm đầu": "/ʌ/", "Ghi chú": "nguyên âm" },
    { "Mạo từ": "an", "Từ": "idea", "Âm đầu": "/aɪ/", "Ghi chú": "nguyên âm" },
    { "Mạo từ": "an", "Từ": "orange", "Âm đầu": "/ɒ/", "Ghi chú": "nguyên âm" }
  ],
},
{
  title: "the · các trường hợp (tài liệu thi)",
  icon: "🎯",
  note: "Đã xác định / lần hai nhắc / duy nhất / hệ thống…",
  rows: [
    { "Trường hợp": "Lần hai nhắc", "Ví dụ": "I saw a dog. The dog was big." },
    { "Trường hợp": "Duy nhất", "Ví dụ": "the sun · the moon · the earth · the sky" },
    { "Trường hợp": "So sánh nhất / quan hệ", "Ví dụ": "the best student · the tallest boy" },
    { "Trường hợp": "Chỉ có 1 trong ngữ cảnh", "Ví dụ": "Close the door. · Open the window." },
    { "Trường hợp": "Sông / biển / đại dương", "Ví dụ": "the Mekong · the Pacific" },
    { "Trường hợp": "Dãy núi", "Ví dụ": "the Alps · the Rockies" },
    { "Trường hợp": "Tên nước số nhiều", "Ví dụ": "the USA · the UK · the Netherlands" },
    { "Trường hợp": "Báo / khách sạn (nhiều tên)", "Ví dụ": "the New York Times · the Hilton" },
    { "Trường hợp": "Nhạc cụ", "Ví dụ": "play the piano · the guitar" },
    { "Trường hợp": "Số thứ tự", "Ví dụ": "the first · the second" },
    { "Trường hợp": "same + danh từ", "Ví dụ": "the same school" },
    { "Trường hợp": "Rạp chiếu phim / nhà hát (Anh hay dùng the)", "Ví dụ": "go to the cinema" }
  ],
},
{
  title: "Không mạo từ (zero article) · các trường hợp (A0–A1 + thi)",
  icon: "∅",
  note: "Không dùng a/an/the khi…",
  rows: [
    { "Trường hợp": "U nói chung", "Ví dụ": "I like music. · She needs water. · Time is money." },
    { "Trường hợp": "C số nhiều nói chung", "Ví dụ": "Dogs are friendly. · Books help us learn." },
    { "Trường hợp": "Tên người", "Ví dụ": "Linh · Tom · Mrs. Nga" },
    { "Trường hợp": "Thành phố / hầu hết tên nước", "Ví dụ": "Hanoi · Vietnam · Japan (≠ the USA/UK)" },
    { "Trường hợp": "Môn học / ngôn ngữ", "Ví dụ": "study English · like history" },
    { "Trường hợp": "Bữa ăn (nói chung)", "Ví dụ": "have breakfast / lunch / dinner" },
    { "Trường hợp": "Thể thao / trò chơi", "Ví dụ": "play football · play chess" },
    { "Trường hợp": "go to + school/work/bed", "Ví dụ": "go to school · go to work · go to bed" },
    { "Trường hợp": "by + phương tiện", "Ví dụ": "by bus · by car · by train · on foot" },
    { "Trường hợp": "at home / at work / in bed", "Ví dụ": "She is at home." },
    { "Trường hợp": "Thứ / tháng (nói chung)", "Ví dụ": "on Monday · in July" },
    { "Trường hợp": "next / last + thời gian", "Ví dụ": "next week · last year" }
  ],
}
];

export const QUANTIFIER_BANKS = [
{
  title: "Lượng từ · khớp C / U (bảng thi)",
  icon: "📊",
  note: "many/a few + C số nhiều · much/a little + U · some (+) · any (−/?) · a lot of = C/U.",
  rows: [
    { "Lượng từ": "many", "Đi với": "C plural", "Ví dụ": "many books · many students · many cars" },
    { "Lượng từ": "much", "Đi với": "U", "Ví dụ": "much water · much time · much money" },
    { "Lượng từ": "a few", "Đi với": "C plural", "Ví dụ": "a few eggs · a few friends" },
    { "Lượng từ": "a little", "Đi với": "U", "Ví dụ": "a little sugar · a little milk" },
    { "Lượng từ": "few (không a)", "Đi với": "C plural", "Ví dụ": "few people came (= hầu như không)" },
    { "Lượng từ": "little (không a)", "Đi với": "U", "Ví dụ": "little time left" },
    { "Lượng từ": "some", "Đi với": "C pl / U (+)", "Ví dụ": "some apples · some rice" },
    { "Lượng từ": "any", "Đi với": "C pl / U (−/?)", "Ví dụ": "I don't have any pens. · any milk?" },
    { "Lượng từ": "a lot of / lots of", "Đi với": "C pl / U", "Ví dụ": "a lot of books · a lot of homework" },
    { "Lượng từ": "plenty of", "Đi với": "C pl / U", "Ví dụ": "plenty of time · plenty of chairs" },
    { "Lượng từ": "a number of", "Đi với": "C plural", "Ví dụ": "a number of students" },
    { "Lượng từ": "an amount of", "Đi với": "U", "Ví dụ": "an amount of money" },
    { "Lượng từ": "several", "Đi với": "C plural", "Ví dụ": "several times" },
    { "Lượng từ": "all / most / some of the", "Đi với": "C/U xác định", "Ví dụ": "most of the water · all of the books" },
    { "Lượng từ": "How many…?", "Đi với": "C plural", "Ví dụ": "How many apples?" },
    { "Lượng từ": "How much…?", "Đi với": "U", "Ví dụ": "How much rice? · How much is it?" }
  ],
},
{
  title: "some / any · tình huống (bẫy đề)",
  icon: "➕",
  note: "Lời mời/yêu cầu lịch sự: dùng some được dù là câu hỏi.",
  rows: [
    { "Tình huống": "Khẳng định", "Dùng": "some", "Ví dụ": "I have some money." },
    { "Tình huống": "Phủ định", "Dùng": "any", "Ví dụ": "I don't have any money." },
    { "Tình huống": "Nghi vấn thường", "Dùng": "any", "Ví dụ": "Do you have any questions?" },
    { "Tình huống": "Mời / đề nghị", "Dùng": "some", "Ví dụ": "Would you like some tea?" },
    { "Tình huống": "Yêu cầu lịch sự", "Dùng": "some", "Ví dụ": "Can I have some water?" },
    { "Tình huống": "Kỳ vọng “có”", "Dùng": "some", "Ví dụ": "Did you buy some bread?" }
  ],
}
];

export const PRESENT_SIMPLE_BANKS = [
{
  title: "Ngôi 3 số ít · thêm -s / -es / -ies (list động từ)",
  icon: "3️⃣",
  note: "he/she/it + V-s/es. I/you/we/they + V1. does/doesn't + V1 (không thêm -s).",
  rows: [
    { "Quy tắc": "+ s", "V1 (nguyên mẫu)": "work", "Ngôi 3": "works" },
    { "Quy tắc": "+ s", "V1 (nguyên mẫu)": "play", "Ngôi 3": "plays" },
    { "Quy tắc": "+ s", "V1 (nguyên mẫu)": "read", "Ngôi 3": "reads" },
    { "Quy tắc": "+ s", "V1 (nguyên mẫu)": "live", "Ngôi 3": "lives" },
    { "Quy tắc": "+ s", "V1 (nguyên mẫu)": "like", "Ngôi 3": "likes" },
    { "Quy tắc": "+ s", "V1 (nguyên mẫu)": "want", "Ngôi 3": "wants" },
    { "Quy tắc": "+ s", "V1 (nguyên mẫu)": "need", "Ngôi 3": "needs" },
    { "Quy tắc": "+ s", "V1 (nguyên mẫu)": "know", "Ngôi 3": "knows" },
    { "Quy tắc": "+ es (s/x/z/ch/sh/o)", "V1 (nguyên mẫu)": "watch", "Ngôi 3": "watches" },
    { "Quy tắc": "+ es", "V1 (nguyên mẫu)": "wash", "Ngôi 3": "washes" },
    { "Quy tắc": "+ es", "V1 (nguyên mẫu)": "teach", "Ngôi 3": "teaches" },
    { "Quy tắc": "+ es", "V1 (nguyên mẫu)": "fix", "Ngôi 3": "fixes" },
    { "Quy tắc": "+ es", "V1 (nguyên mẫu)": "go", "Ngôi 3": "goes" },
    { "Quy tắc": "+ es", "V1 (nguyên mẫu)": "do", "Ngôi 3": "does" },
    { "Quy tắc": "y → ies (phụ âm + y)", "V1 (nguyên mẫu)": "study", "Ngôi 3": "studies" },
    { "Quy tắc": "y → ies", "V1 (nguyên mẫu)": "cry", "Ngôi 3": "cries" },
    { "Quy tắc": "y → ies", "V1 (nguyên mẫu)": "try", "Ngôi 3": "tries" },
    { "Quy tắc": "y → ies", "V1 (nguyên mẫu)": "fly", "Ngôi 3": "flies" },
    { "Quy tắc": "nguyên âm + y → ys", "V1 (nguyên mẫu)": "play", "Ngôi 3": "plays" },
    { "Quy tắc": "nguyên âm + y → ys", "V1 (nguyên mẫu)": "buy", "Ngôi 3": "buys" },
    { "Quy tắc": "bất quy tắc", "V1 (nguyên mẫu)": "have", "Ngôi 3": "has" },
    { "Quy tắc": "bất quy tắc", "V1 (nguyên mẫu)": "be", "Ngôi 3": "is" }
  ],
},
{
  title: "Trạng từ tần suất · vị trí (đi với Hiện tại đơn)",
  icon: "🔁",
  note: "always / usually / often / sometimes / rarely / never — thường **trước động từ thường**, **sau be**.",
  rows: [
    { "Trạng từ": "always", "Tần suất": "~100%", "Ví dụ": "She always gets up early." },
    { "Trạng từ": "usually", "Tần suất": "~80%", "Ví dụ": "I usually walk to school." },
    { "Trạng từ": "often", "Tần suất": "~60%", "Ví dụ": "They often play football." },
    { "Trạng từ": "sometimes", "Tần suất": "~40%", "Ví dụ": "He sometimes cooks." },
    { "Trạng từ": "rarely / seldom", "Tần suất": "~10%", "Ví dụ": "We rarely eat out." },
    { "Trạng từ": "never", "Tần suất": "0%", "Ví dụ": "I never smoke." },
    { "Trạng từ": "every day / week…", "Tần suất": "—", "Ví dụ": "every morning · once a week" },
    { "Trạng từ": "on Mondays…", "Tần suất": "—", "Ví dụ": "On Sundays we rest." }
  ],
}
];

export const TO_BE_BANKS = [
{
  title: "To be · am / is / are (bảng đầy đủ)",
  icon: "🪪",
  note: "Không dùng do/does với to be.",
  rows: [
    { "Chủ ngữ": "I", "Khẳng định (+)": "am", "Phủ định (−)": "am not / I'm not", "Nghi vấn (?)": "Am I …?", "Trả lời ngắn": "Yes, I am. / No, I'm not." },
    { "Chủ ngữ": "you", "Khẳng định (+)": "are", "Phủ định (−)": "are not / aren't", "Nghi vấn (?)": "Are you …?", "Trả lời ngắn": "Yes, you are. / No, you aren't." },
    { "Chủ ngữ": "he", "Khẳng định (+)": "is", "Phủ định (−)": "is not / isn't", "Nghi vấn (?)": "Is he …?", "Trả lời ngắn": "Yes, he is. / No, he isn't." },
    { "Chủ ngữ": "she", "Khẳng định (+)": "is", "Phủ định (−)": "isn't", "Nghi vấn (?)": "Is she …?", "Trả lời ngắn": "Yes, she is. / No, she isn't." },
    { "Chủ ngữ": "it", "Khẳng định (+)": "is", "Phủ định (−)": "isn't", "Nghi vấn (?)": "Is it …?", "Trả lời ngắn": "Yes, it is. / No, it isn't." },
    { "Chủ ngữ": "we", "Khẳng định (+)": "are", "Phủ định (−)": "aren't", "Nghi vấn (?)": "Are we …?", "Trả lời ngắn": "Yes, we are. / No, we aren't." },
    { "Chủ ngữ": "they", "Khẳng định (+)": "are", "Phủ định (−)": "aren't", "Nghi vấn (?)": "Are they …?", "Trả lời ngắn": "Yes, they are. / No, they aren't." },
    { "Chủ ngữ": "singular N", "Khẳng định (+)": "is", "Phủ định (−)": "isn't", "Nghi vấn (?)": "Is the book …?", "Trả lời ngắn": "—" },
    { "Chủ ngữ": "plural N", "Khẳng định (+)": "are", "Phủ định (−)": "aren't", "Nghi vấn (?)": "Are the books …?", "Trả lời ngắn": "—" }
  ],
},
{
  title: "To be · rút gọn hay gặp",
  icon: "✂️",
  rows: [
    { "Đầy đủ": "I am", "Trả lời ngắn": "I'm" },
    { "Đầy đủ": "you are", "Trả lời ngắn": "you're" },
    { "Đầy đủ": "he is", "Trả lời ngắn": "he's" },
    { "Đầy đủ": "she is", "Trả lời ngắn": "she's" },
    { "Đầy đủ": "it is", "Trả lời ngắn": "it's" },
    { "Đầy đủ": "we are", "Trả lời ngắn": "we're" },
    { "Đầy đủ": "they are", "Trả lời ngắn": "they're" },
    { "Đầy đủ": "is not", "Trả lời ngắn": "isn't" },
    { "Đầy đủ": "are not", "Trả lời ngắn": "aren't" },
    { "Đầy đủ": "that is", "Trả lời ngắn": "that's" },
    { "Đầy đủ": "there is", "Trả lời ngắn": "there's" },
    { "Đầy đủ": "who is", "Trả lời ngắn": "who's" }
  ],
}
];

export const POSSESSIVE_BANKS = [
{
  title: "Tính từ sở hữu vs đại từ sở hữu (bảng thi)",
  icon: "🏷️",
  note: "my book (cần danh từ) · mine (đứng một mình).",
  rows: [
    { "Chủ ngữ": "I", "Tính từ sở hữu (cần danh từ)": "my", "Đại từ sở hữu (đứng một mình)": "mine", "Ví dụ": "This is my book. · This is mine." },
    { "Chủ ngữ": "you", "Tính từ sở hữu (cần danh từ)": "your", "Đại từ sở hữu (đứng một mình)": "yours", "Ví dụ": "your bag · yours" },
    { "Chủ ngữ": "he", "Tính từ sở hữu (cần danh từ)": "his", "Đại từ sở hữu (đứng một mình)": "his", "Ví dụ": "his car · his" },
    { "Chủ ngữ": "she", "Tính từ sở hữu (cần danh từ)": "her", "Đại từ sở hữu (đứng một mình)": "hers", "Ví dụ": "her pen · hers" },
    { "Chủ ngữ": "it", "Tính từ sở hữu (cần danh từ)": "its", "Đại từ sở hữu (đứng một mình)": "—", "Ví dụ": "its name (không it's)" },
    { "Chủ ngữ": "we", "Tính từ sở hữu (cần danh từ)": "our", "Đại từ sở hữu (đứng một mình)": "ours", "Ví dụ": "our house · ours" },
    { "Chủ ngữ": "they", "Tính từ sở hữu (cần danh từ)": "their", "Đại từ sở hữu (đứng một mình)": "theirs", "Ví dụ": "their room · theirs" }
  ],
},
{
  title: "'s / s' · sở hữu danh từ",
  icon: "📎",
  rows: [
    { "Trường hợp": "số ít", "Dạng": "N + 's", "Ví dụ": "Tom's bike · the girl's bag" },
    { "Trường hợp": "số nhiều tận -s", "Dạng": "N + '", "Ví dụ": "the students' books · the boys' room" },
    { "Trường hợp": "số nhiều bất quy tắc", "Dạng": "N + 's", "Ví dụ": "the children's toys · the men's room" },
    { "Trường hợp": "tên riêng tận s", "Dạng": "'s hoặc '", "Ví dụ": "James's / James' car" },
    { "Trường hợp": "of + vật / cụm dài", "Dạng": "the N of N", "Ví dụ": "the door of the room · the capital of Vietnam" },
    { "Trường hợp": "its vs it's", "Dạng": "its = sở hữu; it's = it is", "Ví dụ": "The cat licked its paw. · It's cold." }
  ],
}
];

export const DEMONSTRATIVE_BANKS = [
{
  title: "This / That / These / Those (đại từ chỉ định)",
  icon: "👆",
  note: "Gần = this/these · Xa = that/those. Khớp số ít/số nhiều.",
  rows: [
    { "Từ": "this", "Số": "số ít", "Khoảng cách": "gần", "Ví dụ": "This is my pen. · This book is new." },
    { "Từ": "that", "Số": "số ít", "Khoảng cách": "xa", "Ví dụ": "That is her car. · That house is old." },
    { "Từ": "these", "Số": "số nhiều", "Khoảng cách": "gần", "Ví dụ": "These are my keys. · These books…" },
    { "Từ": "those", "Số": "số nhiều", "Khoảng cách": "xa", "Ví dụ": "Those are stars. · Those people…" }
  ],
}
];

export const THERE_IS_BANKS = [
{
  title: "There is / There are (có…)",
  icon: "📍",
  note: "There is + số ít/U · There are + số nhiều. Phủ định: isn't / aren't · any.",
  rows: [
    { "Dạng": "There is + C ít", "Ví dụ": "There is a book on the table." },
    { "Dạng": "There is + U", "Ví dụ": "There is some water." },
    { "Dạng": "There are + C nhiều", "Ví dụ": "There are three chairs." },
    { "Dạng": "There isn't + a/any", "Ví dụ": "There isn't a cat. · There isn't any milk." },
    { "Dạng": "There aren't + any", "Ví dụ": "There aren't any eggs." },
    { "Dạng": "Is there …?", "Ví dụ": "Is there a bank near here?" },
    { "Dạng": "Are there …?", "Ví dụ": "Are there any questions?" },
    { "Dạng": "There's (rút gọn)", "Ví dụ": "There's a problem." }
  ],
}
];

export const PREP_PLACE_BANKS = [
{
  title: "Giới từ nơi chốn · in / on / at + list",
  icon: "🗺️",
  note: "in = trong không gian · on = trên bề mặt · at = điểm.",
  rows: [
    { "Giới từ": "in", "Trường hợp": "phòng / hộp / túi", "Ví dụ": "in the room · in the box · in my bag" },
    { "Giới từ": "in", "Trường hợp": "thành phố / nước", "Ví dụ": "in Hanoi · in Vietnam" },
    { "Giới từ": "in", "Trường hợp": "sách / ảnh", "Ví dụ": "in the book · in the photo" },
    { "Giới từ": "in", "Trường hợp": "xe hơi / taxi (Anh)", "Ví dụ": "in the car · in a taxi" },
    { "Giới từ": "on", "Trường hợp": "bề mặt", "Ví dụ": "on the table · on the wall · on the floor" },
    { "Giới từ": "on", "Trường hợp": "đường / tầng", "Ví dụ": "on the street · on the second floor" },
    { "Giới từ": "on", "Trường hợp": "phương tiện công cộng", "Ví dụ": "on the bus · on the train · on a plane" },
    { "Giới từ": "on", "Trường hợp": "TV / internet / điện thoại", "Ví dụ": "on TV · on the internet · on the phone" },
    { "Giới từ": "at", "Trường hợp": "điểm / địa điểm cụ thể", "Ví dụ": "at the door · at the station · at school" },
    { "Giới từ": "at", "Trường hợp": "sự kiện / địa chỉ số nhà", "Ví dụ": "at a party · at 12 Le Loi Street" },
    { "Giới từ": "at", "Trường hợp": "home / work", "Ví dụ": "at home · at work" },
    { "Giới từ": "under", "Trường hợp": "dưới", "Ví dụ": "under the table" },
    { "Giới từ": "over / above", "Trường hợp": "phía trên", "Ví dụ": "over the bridge · above the bed" },
    { "Giới từ": "between", "Trường hợp": "giữa 2", "Ví dụ": "between A and B" },
    { "Giới từ": "among", "Trường hợp": "giữa nhiều", "Ví dụ": "among the students" },
    { "Giới từ": "next to / beside", "Trường hợp": "bên cạnh", "Ví dụ": "next to the bank" },
    { "Giới từ": "in front of", "Trường hợp": "phía trước", "Ví dụ": "in front of the school" },
    { "Giới từ": "behind", "Trường hợp": "phía sau", "Ví dụ": "behind the door" },
    { "Giới từ": "near / by", "Trường hợp": "gần", "Ví dụ": "near the park" },
    { "Giới từ": "opposite", "Trường hợp": "đối diện", "Ví dụ": "opposite the cinema" }
  ],
}
];

export const PREP_TIME_BANKS = [
{
  title: "Giới từ thời gian · in / on / at + list",
  icon: "⏰",
  note: "in = tháng/năm/buổi · on = ngày/thứ · at = giờ/điểm thời gian.",
  rows: [
    { "Giới từ": "at", "Trường hợp": "giờ", "Ví dụ": "at 7 o'clock · at half past six" },
    { "Giới từ": "at", "Trường hợp": "điểm thời gian", "Ví dụ": "at noon · at midnight · at night · at the weekend (BrE)" },
    { "Giới từ": "at", "Trường hợp": "bữa / dịp lễ (điểm)", "Ví dụ": "at breakfast · at Christmas" },
    { "Giới từ": "on", "Trường hợp": "thứ / ngày", "Ví dụ": "on Monday · on 1 May · on my birthday" },
    { "Giới từ": "on", "Trường hợp": "buổi + ngày", "Ví dụ": "on Monday morning · on Friday night" },
    { "Giới từ": "on", "Trường hợp": "weekend (Mỹ)", "Ví dụ": "on the weekend" },
    { "Giới từ": "in", "Trường hợp": "tháng / năm / mùa", "Ví dụ": "in July · in 2020 · in summer" },
    { "Giới từ": "in", "Trường hợp": "buổi (không kèm ngày)", "Ví dụ": "in the morning · in the afternoon · in the evening" },
    { "Giới từ": "in", "Trường hợp": "khoảng thời gian", "Ví dụ": "in five minutes · in two weeks" },
    { "Giới từ": "∅", "Trường hợp": "next / last / this / every", "Ví dụ": "next week · last year · this morning · every day" }
  ],
}
];

export const COMPARATIVE_BANKS = [
{
  title: "So sánh hơn / nhất · có quy tắc + bất quy tắc (list)",
  icon: "📏",
  note: "1 âm tiết: -er/-est · tính từ dài: more/most · bất quy tắc học thuộc.",
  rows: [
    { "Tính từ": "tall", "So sánh hơn": "taller", "So sánh nhất": "the tallest" },
    { "Tính từ": "short", "So sánh hơn": "shorter", "So sánh nhất": "the shortest" },
    { "Tính từ": "big", "So sánh hơn": "bigger", "So sánh nhất": "the biggest" },
    { "Tính từ": "hot", "So sánh hơn": "hotter", "So sánh nhất": "the hottest" },
    { "Tính từ": "happy", "So sánh hơn": "happier", "So sánh nhất": "the happiest" },
    { "Tính từ": "easy", "So sánh hơn": "easier", "So sánh nhất": "the easiest" },
    { "Tính từ": "nice", "So sánh hơn": "nicer", "So sánh nhất": "the nicest" },
    { "Tính từ": "large", "So sánh hơn": "larger", "So sánh nhất": "the largest" },
    { "Tính từ": "beautiful", "So sánh hơn": "more beautiful", "So sánh nhất": "the most beautiful" },
    { "Tính từ": "expensive", "So sánh hơn": "more expensive", "So sánh nhất": "the most expensive" },
    { "Tính từ": "interesting", "So sánh hơn": "more interesting", "So sánh nhất": "the most interesting" },
    { "Tính từ": "good", "So sánh hơn": "better", "So sánh nhất": "the best" },
    { "Tính từ": "bad", "So sánh hơn": "worse", "So sánh nhất": "the worst" },
    { "Tính từ": "far", "So sánh hơn": "farther/further", "So sánh nhất": "the farthest/furthest" },
    { "Tính từ": "many / much", "So sánh hơn": "more", "So sánh nhất": "the most" },
    { "Tính từ": "little", "So sánh hơn": "less", "So sánh nhất": "the least" },
    { "Tính từ": "old", "So sánh hơn": "older / elder", "So sánh nhất": "the oldest / eldest" }
  ],
}
];

export function banksForSlug(slug) {
  const base = {
    'countable-uncountable': UNCOUNTABLE_BANKS,
    'plural-nouns': PLURAL_BANKS,
    'past-simple': [IRREGULAR_PAST_BANK],
    articles: ARTICLE_BANKS,
    quantifiers: QUANTIFIER_BANKS,
    'present-simple': PRESENT_SIMPLE_BANKS,
    'adverbs-frequency': [PRESENT_SIMPLE_BANKS[1]],
    'verb-to-be': TO_BE_BANKS,
    possessives: POSSESSIVE_BANKS,
    demonstratives: DEMONSTRATIVE_BANKS,
    'there-is-there-are': THERE_IS_BANKS,
    'prepositions-place': PREP_PLACE_BANKS,
    'prepositions-time': PREP_TIME_BANKS,
    'comparatives-superlatives': COMPARATIVE_BANKS,
  };
  const fromBase = base[slug] || null;
  const fromB2 = batch2ForSlug(slug);
  const fromB3 = batch3ForSlug(slug);
  // gộp nếu nhiều nguồn (demonstratives / there-is…)
  const parts = [fromBase, fromB2, fromB3].filter(Boolean);
  if (!parts.length) return null;
  if (parts.length === 1) return parts[0];
  return parts.flat();
}

export function bankStats() {
  const slugs = [
    // batch1
    'countable-uncountable',
    'plural-nouns',
    'past-simple',
    'articles',
    'quantifiers',
    'present-simple',
    'verb-to-be',
    'possessives',
    'demonstratives',
    'there-is-there-are',
    'prepositions-place',
    'prepositions-time',
    'comparatives-superlatives',
    'adverbs-frequency',
    // batch2
    'personal-pronouns',
    'have-got',
    'wh-questions',
    'present-continuous',
    'past-continuous',
    'be-going-to',
    'future-will',
    'imperatives',
    'adjectives-basic',
    'modals-ability',
    'modals-permission',
    'modals-obligation',
    'modals-advice',
    'conditionals-0-1',
    // batch3 A2
    'present-perfect',
    'present-perfect-continuous',
    'past-perfect',
    'passive-voice',
    'reported-speech',
    'relative-clauses',
    'gerunds-infinitives',
    'used-to',
    'question-tags',
    'second-conditional',
    'third-conditional',
    'future-continuous',
    'modals-deduction',
    'conjunctions-linking',
    'phrasal-verbs',
  ];
  const out = {};
  for (const slug of slugs) {
    const banks = banksForSlug(slug) || [];
    out[slug] = {
      tables: banks.length,
      rows: banks.reduce((n, b) => n + (b.rows?.length || 0), 0),
    };
  }
  return out;
}
